package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlConfigCruxModel;
import com.yd.iotbusiness.mapper.model.LlConfigCruxModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlConfigCruxModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    long countByExample(LlConfigCruxModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int deleteByExample(LlConfigCruxModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int insert(LlConfigCruxModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int insertSelective(LlConfigCruxModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    List<LlConfigCruxModel> selectByExample(LlConfigCruxModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    LlConfigCruxModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlConfigCruxModel row, @Param("example") LlConfigCruxModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlConfigCruxModel row, @Param("example") LlConfigCruxModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlConfigCruxModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_config_crux
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlConfigCruxModel row);
}