package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlCronsModel;
import com.yd.iotbusiness.mapper.model.LlCronsModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlCronsModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    long countByExample(LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int deleteByExample(LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int insert(LlCronsModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int insertSelective(LlCronsModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    List<LlCronsModel> selectByExampleWithBLOBs(LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    List<LlCronsModel> selectByExample(LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    LlCronsModel selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlCronsModel row, @Param("example") LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") LlCronsModel row, @Param("example") LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlCronsModel row, @Param("example") LlCronsModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlCronsModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LlCronsModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_crons
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlCronsModel row);
}