package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlDictionaryModel;
import com.yd.iotbusiness.mapper.model.LlDictionaryModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlDictionaryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    long countByExample(LlDictionaryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int deleteByExample(LlDictionaryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int insert(LlDictionaryModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int insertSelective(LlDictionaryModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    List<LlDictionaryModel> selectByExample(LlDictionaryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    LlDictionaryModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlDictionaryModel row, @Param("example") LlDictionaryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlDictionaryModel row, @Param("example") LlDictionaryModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlDictionaryModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_dictionary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlDictionaryModel row);
}