package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlOperatorLogModel;
import com.yd.iotbusiness.mapper.model.LlOperatorLogModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlOperatorLogModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    long countByExample(LlOperatorLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int deleteByExample(LlOperatorLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int insert(LlOperatorLogModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int insertSelective(LlOperatorLogModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    List<LlOperatorLogModel> selectByExample(LlOperatorLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    LlOperatorLogModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlOperatorLogModel row, @Param("example") LlOperatorLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlOperatorLogModel row, @Param("example") LlOperatorLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlOperatorLogModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_operator_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlOperatorLogModel row);
}