package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlReportRoleAdminRelationModel;
import com.yd.iotbusiness.mapper.model.LlReportRoleAdminRelationModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlReportRoleAdminRelationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    long countByExample(LlReportRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int deleteByExample(LlReportRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int insert(LlReportRoleAdminRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int insertSelective(LlReportRoleAdminRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    List<LlReportRoleAdminRelationModel> selectByExample(LlReportRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    LlReportRoleAdminRelationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlReportRoleAdminRelationModel row, @Param("example") LlReportRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlReportRoleAdminRelationModel row, @Param("example") LlReportRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlReportRoleAdminRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlReportRoleAdminRelationModel row);
}