package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlReportRoleRelationModel;
import com.yd.iotbusiness.mapper.model.LlReportRoleRelationModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlReportRoleRelationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    long countByExample(LlReportRoleRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int deleteByExample(LlReportRoleRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int insert(LlReportRoleRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int insertSelective(LlReportRoleRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    List<LlReportRoleRelationModel> selectByExample(LlReportRoleRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    LlReportRoleRelationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlReportRoleRelationModel row, @Param("example") LlReportRoleRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlReportRoleRelationModel row, @Param("example") LlReportRoleRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlReportRoleRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_role_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlReportRoleRelationModel row);
}