package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlReportSimpleModel;
import com.yd.iotbusiness.mapper.model.LlReportSimpleModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlReportSimpleModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    long countByExample(LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int deleteByExample(LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int insert(LlReportSimpleModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int insertSelective(LlReportSimpleModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    List<LlReportSimpleModel> selectByExampleWithBLOBs(LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    List<LlReportSimpleModel> selectByExample(LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    LlReportSimpleModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlReportSimpleModel row, @Param("example") LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") LlReportSimpleModel row, @Param("example") LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlReportSimpleModel row, @Param("example") LlReportSimpleModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlReportSimpleModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LlReportSimpleModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlReportSimpleModel row);
}