package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlSystemMenuModel;
import com.yd.iotbusiness.mapper.model.LlSystemMenuModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlSystemMenuModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    long countByExample(LlSystemMenuModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int deleteByExample(LlSystemMenuModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int insert(LlSystemMenuModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int insertSelective(LlSystemMenuModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    List<LlSystemMenuModel> selectByExample(LlSystemMenuModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    LlSystemMenuModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlSystemMenuModel row, @Param("example") LlSystemMenuModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlSystemMenuModel row, @Param("example") LlSystemMenuModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlSystemMenuModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlSystemMenuModel row);
}