package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlSystemLogTemplateModel;
import com.yd.iotbusiness.mapper.model.LlSystemLogTemplateModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlSystemLogTemplateModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    long countByExample(LlSystemLogTemplateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int deleteByExample(LlSystemLogTemplateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int insert(LlSystemLogTemplateModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int insertSelective(LlSystemLogTemplateModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    List<LlSystemLogTemplateModel> selectByExample(LlSystemLogTemplateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    LlSystemLogTemplateModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlSystemLogTemplateModel row, @Param("example") LlSystemLogTemplateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlSystemLogTemplateModel row, @Param("example") LlSystemLogTemplateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlSystemLogTemplateModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_log_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlSystemLogTemplateModel row);
}