package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlSystemRoleMenuRelationModel;
import com.yd.iotbusiness.mapper.model.LlSystemRoleMenuRelationModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlSystemRoleMenuRelationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    long countByExample(LlSystemRoleMenuRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int deleteByExample(LlSystemRoleMenuRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int insert(LlSystemRoleMenuRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int insertSelective(LlSystemRoleMenuRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    List<LlSystemRoleMenuRelationModel> selectByExample(LlSystemRoleMenuRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    LlSystemRoleMenuRelationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlSystemRoleMenuRelationModel row, @Param("example") LlSystemRoleMenuRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlSystemRoleMenuRelationModel row, @Param("example") LlSystemRoleMenuRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlSystemRoleMenuRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_menu_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlSystemRoleMenuRelationModel row);
}