package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LlSystemRoleAdminRelationModel;
import com.yd.iotbusiness.mapper.model.LlSystemRoleAdminRelationModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LlSystemRoleAdminRelationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    long countByExample(LlSystemRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int deleteByExample(LlSystemRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int insert(LlSystemRoleAdminRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int insertSelective(LlSystemRoleAdminRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    List<LlSystemRoleAdminRelationModel> selectByExample(LlSystemRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    LlSystemRoleAdminRelationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlSystemRoleAdminRelationModel row, @Param("example") LlSystemRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlSystemRoleAdminRelationModel row, @Param("example") LlSystemRoleAdminRelationModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlSystemRoleAdminRelationModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_system_role_admin_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlSystemRoleAdminRelationModel row);
}