package com.yd.iotbusiness.mapper.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yd.iotbusiness.mapper.model.LlWechatOriginalInfoModel;
import com.yd.iotbusiness.mapper.model.LlWechatOriginalInfoModelExample;

public interface LlWechatOriginalInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    long countByExample(LlWechatOriginalInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int deleteByExample(LlWechatOriginalInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int insert(LlWechatOriginalInfoModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int insertSelective(LlWechatOriginalInfoModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    List<LlWechatOriginalInfoModel> selectByExample(LlWechatOriginalInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    LlWechatOriginalInfoModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LlWechatOriginalInfoModel row, @Param("example") LlWechatOriginalInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LlWechatOriginalInfoModel row, @Param("example") LlWechatOriginalInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LlWechatOriginalInfoModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_wechat_original_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LlWechatOriginalInfoModel row);
}