package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmBilldetailModel;
import com.yd.iotbusiness.mapper.model.LmBilldetailModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmBilldetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    long countByExample(LmBilldetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int deleteByExample(LmBilldetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int insert(LmBilldetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int insertSelective(LmBilldetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    List<LmBilldetailModel> selectByExample(LmBilldetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    LmBilldetailModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmBilldetailModel row, @Param("example") LmBilldetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmBilldetailModel row, @Param("example") LmBilldetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmBilldetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_billdetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmBilldetailModel row);
}