package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmFeedetailModel;
import com.yd.iotbusiness.mapper.model.LmFeedetailModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmFeedetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    long countByExample(LmFeedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int deleteByExample(LmFeedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int insert(LmFeedetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int insertSelective(LmFeedetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    List<LmFeedetailModel> selectByExample(LmFeedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    LmFeedetailModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmFeedetailModel row, @Param("example") LmFeedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmFeedetailModel row, @Param("example") LmFeedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmFeedetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_feedetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmFeedetailModel row);
}