package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmFeeModel;
import com.yd.iotbusiness.mapper.model.LmFeeModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmFeeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    long countByExample(LmFeeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int deleteByExample(LmFeeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int insert(LmFeeModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int insertSelective(LmFeeModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    List<LmFeeModel> selectByExample(LmFeeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    LmFeeModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmFeeModel row, @Param("example") LmFeeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmFeeModel row, @Param("example") LmFeeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmFeeModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_fee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmFeeModel row);
}