package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmPaydetailModel;
import com.yd.iotbusiness.mapper.model.LmPaydetailModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmPaydetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    long countByExample(LmPaydetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int deleteByExample(LmPaydetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int insert(LmPaydetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int insertSelective(LmPaydetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    List<LmPaydetailModel> selectByExample(LmPaydetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    LmPaydetailModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmPaydetailModel row, @Param("example") LmPaydetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmPaydetailModel row, @Param("example") LmPaydetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmPaydetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paydetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmPaydetailModel row);
}