package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmPaperrecordModel;
import com.yd.iotbusiness.mapper.model.LmPaperrecordModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmPaperrecordModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    long countByExample(LmPaperrecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int deleteByExample(LmPaperrecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int insert(LmPaperrecordModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int insertSelective(LmPaperrecordModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    List<LmPaperrecordModel> selectByExample(LmPaperrecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    LmPaperrecordModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmPaperrecordModel row, @Param("example") LmPaperrecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmPaperrecordModel row, @Param("example") LmPaperrecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmPaperrecordModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_paperrecord
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmPaperrecordModel row);
}