package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmPricedetailModel;
import com.yd.iotbusiness.mapper.model.LmPricedetailModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmPricedetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    long countByExample(LmPricedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int deleteByExample(LmPricedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int insert(LmPricedetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int insertSelective(LmPricedetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    List<LmPricedetailModel> selectByExample(LmPricedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    LmPricedetailModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmPricedetailModel row, @Param("example") LmPricedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmPricedetailModel row, @Param("example") LmPricedetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmPricedetailModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_pricedetail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmPricedetailModel row);
}