package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmPriceModel;
import com.yd.iotbusiness.mapper.model.LmPriceModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmPriceModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    long countByExample(LmPriceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int deleteByExample(LmPriceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int insert(LmPriceModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int insertSelective(LmPriceModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    List<LmPriceModel> selectByExample(LmPriceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    LmPriceModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmPriceModel row, @Param("example") LmPriceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmPriceModel row, @Param("example") LmPriceModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmPriceModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmPriceModel row);
}