package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmRecordmonthModel;
import com.yd.iotbusiness.mapper.model.LmRecordmonthModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmRecordmonthModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    long countByExample(LmRecordmonthModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int deleteByExample(LmRecordmonthModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int insert(LmRecordmonthModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int insertSelective(LmRecordmonthModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    List<LmRecordmonthModel> selectByExample(LmRecordmonthModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    LmRecordmonthModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmRecordmonthModel row, @Param("example") LmRecordmonthModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmRecordmonthModel row, @Param("example") LmRecordmonthModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmRecordmonthModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordmonth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmRecordmonthModel row);
}