package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmReadingrateModel;
import com.yd.iotbusiness.mapper.model.LmReadingrateModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmReadingrateModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    long countByExample(LmReadingrateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int deleteByExample(LmReadingrateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int insert(LmReadingrateModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int insertSelective(LmReadingrateModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    List<LmReadingrateModel> selectByExample(LmReadingrateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    LmReadingrateModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmReadingrateModel row, @Param("example") LmReadingrateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmReadingrateModel row, @Param("example") LmReadingrateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmReadingrateModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_readingrate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmReadingrateModel row);
}