package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.LmRecorddayModel;
import com.yd.iotbusiness.mapper.model.LmRecorddayModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LmRecorddayModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    long countByExample(LmRecorddayModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int deleteByExample(LmRecorddayModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int insert(LmRecorddayModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int insertSelective(LmRecorddayModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    List<LmRecorddayModel> selectByExample(LmRecorddayModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    LmRecorddayModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LmRecorddayModel row, @Param("example") LmRecorddayModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LmRecorddayModel row, @Param("example") LmRecorddayModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LmRecorddayModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_recordday
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LmRecorddayModel row);
}