package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.QsCmdModel;
import com.yd.iotbusiness.mapper.model.QsCmdModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QsCmdModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    long countByExample(QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int deleteByExample(QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int insert(QsCmdModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int insertSelective(QsCmdModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    List<QsCmdModel> selectByExampleWithBLOBs(QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    List<QsCmdModel> selectByExample(QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    QsCmdModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") QsCmdModel row, @Param("example") QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") QsCmdModel row, @Param("example") QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") QsCmdModel row, @Param("example") QsCmdModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QsCmdModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(QsCmdModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QsCmdModel row);
}