package com.yd.iotbusiness.mapper.dao;

import com.yd.iotbusiness.mapper.model.QsMeterModel;
import com.yd.iotbusiness.mapper.model.QsMeterModel;
import com.yd.iotbusiness.mapper.model.QsMeterModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QsMeterModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    long countByExample(QsMeterModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int deleteByExample(QsMeterModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int insert(QsMeterModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int insertSelective(QsMeterModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    List<QsMeterModel> selectByExample(QsMeterModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    QsMeterModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") QsMeterModel row, @Param("example") QsMeterModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") QsMeterModel row, @Param("example") QsMeterModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QsMeterModel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_meter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QsMeterModel row);
}