package com.yd.iotbusiness.mapper.model;

import java.io.Serializable;

public class LlReportSimpleModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.column_codes
     *
     * @mbg.generated
     */
    private String columnCodes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.column_names
     *
     * @mbg.generated
     */
    private String columnNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.seq
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ll_report_simple.data_sql
     *
     * @mbg.generated
     */
    private String dataSql;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.id
     *
     * @return the value of ll_report_simple.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.id
     *
     * @param id the value for ll_report_simple.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.name
     *
     * @return the value of ll_report_simple.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.name
     *
     * @param name the value for ll_report_simple.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.code
     *
     * @return the value of ll_report_simple.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.code
     *
     * @param code the value for ll_report_simple.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.status
     *
     * @return the value of ll_report_simple.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.status
     *
     * @param status the value for ll_report_simple.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.column_codes
     *
     * @return the value of ll_report_simple.column_codes
     *
     * @mbg.generated
     */
    public String getColumnCodes() {
        return columnCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.column_codes
     *
     * @param columnCodes the value for ll_report_simple.column_codes
     *
     * @mbg.generated
     */
    public void setColumnCodes(String columnCodes) {
        this.columnCodes = columnCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.column_names
     *
     * @return the value of ll_report_simple.column_names
     *
     * @mbg.generated
     */
    public String getColumnNames() {
        return columnNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.column_names
     *
     * @param columnNames the value for ll_report_simple.column_names
     *
     * @mbg.generated
     */
    public void setColumnNames(String columnNames) {
        this.columnNames = columnNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.seq
     *
     * @return the value of ll_report_simple.seq
     *
     * @mbg.generated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.seq
     *
     * @param seq the value for ll_report_simple.seq
     *
     * @mbg.generated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.remark
     *
     * @return the value of ll_report_simple.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.remark
     *
     * @param remark the value for ll_report_simple.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ll_report_simple.data_sql
     *
     * @return the value of ll_report_simple.data_sql
     *
     * @mbg.generated
     */
    public String getDataSql() {
        return dataSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ll_report_simple.data_sql
     *
     * @param dataSql the value for ll_report_simple.data_sql
     *
     * @mbg.generated
     */
    public void setDataSql(String dataSql) {
        this.dataSql = dataSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", status=").append(status);
        sb.append(", columnCodes=").append(columnCodes);
        sb.append(", columnNames=").append(columnNames);
        sb.append(", seq=").append(seq);
        sb.append(", remark=").append(remark);
        sb.append(", dataSql=").append(dataSql);
        sb.append("]");
        return sb.toString();
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }
}