package com.yd.iotbusiness.mapper.model;

import java.util.ArrayList;
import java.util.List;

public class LlReportSimpleModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public LlReportSimpleModelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }

    public LlReportSimpleModelExample(Object pageInation) {
        oredCriteria = new ArrayList<>();
        LlReportSimpleModel model = (LlReportSimpleModel)pageInation;
        this.setPage(model.getPage());
        this.setRows(model.getRows());
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id =", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <>", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("id >", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id >=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            if (value != null) {
                addCriterion("id <", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` =", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` <>", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            if (value != null) {
                addCriterion("`name` >", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` >=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            if (value != null) {
                addCriterion("`name` <", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` <=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            if (value != null) {
                addCriterion("`name` like", "%"+value+"%", "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            if (value != null) {
                addCriterion("`name` not like", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            if (value != null) {
                addCriterion("code =", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("code <>", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            if (value != null) {
                addCriterion("code >", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("code >=", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            if (value != null) {
                addCriterion("code <", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("code <=", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            if (value != null) {
                addCriterion("code like", "%"+value+"%", "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            if (value != null) {
                addCriterion("code not like", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            if (value != null) {
                addCriterion("`status` =", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("`status` <>", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("`status` >", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("`status` >=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            if (value != null) {
                addCriterion("`status` <", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("`status` <=", value, "status");
            }
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andColumnCodesIsNull() {
            addCriterion("column_codes is null");
            return (Criteria) this;
        }

        public Criteria andColumnCodesIsNotNull() {
            addCriterion("column_codes is not null");
            return (Criteria) this;
        }

        public Criteria andColumnCodesEqualTo(String value) {
            if (value != null) {
                addCriterion("column_codes =", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesNotEqualTo(String value) {
            if (value != null) {
                addCriterion("column_codes <>", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesGreaterThan(String value) {
            if (value != null) {
                addCriterion("column_codes >", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("column_codes >=", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesLessThan(String value) {
            if (value != null) {
                addCriterion("column_codes <", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("column_codes <=", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesLike(String value) {
            if (value != null) {
                addCriterion("column_codes like", "%"+value+"%", "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesNotLike(String value) {
            if (value != null) {
                addCriterion("column_codes not like", value, "columnCodes");
            }
            return (Criteria) this;
        }

        public Criteria andColumnCodesIn(List<String> values) {
            addCriterion("column_codes in", values, "columnCodes");
            return (Criteria) this;
        }

        public Criteria andColumnCodesNotIn(List<String> values) {
            addCriterion("column_codes not in", values, "columnCodes");
            return (Criteria) this;
        }

        public Criteria andColumnCodesBetween(String value1, String value2) {
            addCriterion("column_codes between", value1, value2, "columnCodes");
            return (Criteria) this;
        }

        public Criteria andColumnCodesNotBetween(String value1, String value2) {
            addCriterion("column_codes not between", value1, value2, "columnCodes");
            return (Criteria) this;
        }

        public Criteria andColumnNamesIsNull() {
            addCriterion("column_names is null");
            return (Criteria) this;
        }

        public Criteria andColumnNamesIsNotNull() {
            addCriterion("column_names is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNamesEqualTo(String value) {
            if (value != null) {
                addCriterion("column_names =", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesNotEqualTo(String value) {
            if (value != null) {
                addCriterion("column_names <>", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesGreaterThan(String value) {
            if (value != null) {
                addCriterion("column_names >", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("column_names >=", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesLessThan(String value) {
            if (value != null) {
                addCriterion("column_names <", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("column_names <=", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesLike(String value) {
            if (value != null) {
                addCriterion("column_names like", "%"+value+"%", "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesNotLike(String value) {
            if (value != null) {
                addCriterion("column_names not like", value, "columnNames");
            }
            return (Criteria) this;
        }

        public Criteria andColumnNamesIn(List<String> values) {
            addCriterion("column_names in", values, "columnNames");
            return (Criteria) this;
        }

        public Criteria andColumnNamesNotIn(List<String> values) {
            addCriterion("column_names not in", values, "columnNames");
            return (Criteria) this;
        }

        public Criteria andColumnNamesBetween(String value1, String value2) {
            addCriterion("column_names between", value1, value2, "columnNames");
            return (Criteria) this;
        }

        public Criteria andColumnNamesNotBetween(String value1, String value2) {
            addCriterion("column_names not between", value1, value2, "columnNames");
            return (Criteria) this;
        }

        public Criteria andSeqIsNull() {
            addCriterion("seq is null");
            return (Criteria) this;
        }

        public Criteria andSeqIsNotNull() {
            addCriterion("seq is not null");
            return (Criteria) this;
        }

        public Criteria andSeqEqualTo(Integer value) {
            if (value != null) {
                addCriterion("seq =", value, "seq");
            }
            return (Criteria) this;
        }

        public Criteria andSeqNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("seq <>", value, "seq");
            }
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("seq >", value, "seq");
            }
            return (Criteria) this;
        }

        public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("seq >=", value, "seq");
            }
            return (Criteria) this;
        }

        public Criteria andSeqLessThan(Integer value) {
            if (value != null) {
                addCriterion("seq <", value, "seq");
            }
            return (Criteria) this;
        }

        public Criteria andSeqLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("seq <=", value, "seq");
            }
            return (Criteria) this;
        }

        public Criteria andSeqIn(List<Integer> values) {
            addCriterion("seq in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotIn(List<Integer> values) {
            addCriterion("seq not in", values, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqBetween(Integer value1, Integer value2) {
            addCriterion("seq between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("seq not between", value1, value2, "seq");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            if (value != null) {
                addCriterion("remark =", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            if (value != null) {
                addCriterion("remark <>", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            if (value != null) {
                addCriterion("remark >", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("remark >=", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            if (value != null) {
                addCriterion("remark <", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("remark <=", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            if (value != null) {
                addCriterion("remark like", "%"+value+"%", "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            if (value != null) {
                addCriterion("remark not like", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ll_report_simple
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ll_report_simple
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}