package com.yd.iotbusiness.mapper.model;

import java.util.ArrayList;
import java.util.List;

public class LlSupplierModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public LlSupplierModelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }

    public LlSupplierModelExample(Object pageInation) {
        oredCriteria = new ArrayList<>();
        LlSupplierModel model = (LlSupplierModel)pageInation;
        this.setPage(model.getPage());
        this.setRows(model.getRows());
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id =", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <>", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("id >", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id >=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            if (value != null) {
                addCriterion("id <", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` =", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` <>", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            if (value != null) {
                addCriterion("`name` >", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` >=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            if (value != null) {
                addCriterion("`name` <", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` <=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            if (value != null) {
                addCriterion("`name` like", "%"+value+"%", "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            if (value != null) {
                addCriterion("`name` not like", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            if (value != null) {
                addCriterion("code =", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("code <>", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            if (value != null) {
                addCriterion("code >", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("code >=", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            if (value != null) {
                addCriterion("code <", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("code <=", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            if (value != null) {
                addCriterion("code like", "%"+value+"%", "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            if (value != null) {
                addCriterion("code not like", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andServerUrlIsNull() {
            addCriterion("server_url is null");
            return (Criteria) this;
        }

        public Criteria andServerUrlIsNotNull() {
            addCriterion("server_url is not null");
            return (Criteria) this;
        }

        public Criteria andServerUrlEqualTo(String value) {
            if (value != null) {
                addCriterion("server_url =", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlNotEqualTo(String value) {
            if (value != null) {
                addCriterion("server_url <>", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlGreaterThan(String value) {
            if (value != null) {
                addCriterion("server_url >", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("server_url >=", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlLessThan(String value) {
            if (value != null) {
                addCriterion("server_url <", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("server_url <=", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlLike(String value) {
            if (value != null) {
                addCriterion("server_url like", "%"+value+"%", "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlNotLike(String value) {
            if (value != null) {
                addCriterion("server_url not like", value, "serverUrl");
            }
            return (Criteria) this;
        }

        public Criteria andServerUrlIn(List<String> values) {
            addCriterion("server_url in", values, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotIn(List<String> values) {
            addCriterion("server_url not in", values, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlBetween(String value1, String value2) {
            addCriterion("server_url between", value1, value2, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotBetween(String value1, String value2) {
            addCriterion("server_url not between", value1, value2, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andLoginKeyIsNull() {
            addCriterion("login_key is null");
            return (Criteria) this;
        }

        public Criteria andLoginKeyIsNotNull() {
            addCriterion("login_key is not null");
            return (Criteria) this;
        }

        public Criteria andLoginKeyEqualTo(String value) {
            if (value != null) {
                addCriterion("login_key =", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyNotEqualTo(String value) {
            if (value != null) {
                addCriterion("login_key <>", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyGreaterThan(String value) {
            if (value != null) {
                addCriterion("login_key >", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("login_key >=", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyLessThan(String value) {
            if (value != null) {
                addCriterion("login_key <", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("login_key <=", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyLike(String value) {
            if (value != null) {
                addCriterion("login_key like", "%"+value+"%", "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyNotLike(String value) {
            if (value != null) {
                addCriterion("login_key not like", value, "loginKey");
            }
            return (Criteria) this;
        }

        public Criteria andLoginKeyIn(List<String> values) {
            addCriterion("login_key in", values, "loginKey");
            return (Criteria) this;
        }

        public Criteria andLoginKeyNotIn(List<String> values) {
            addCriterion("login_key not in", values, "loginKey");
            return (Criteria) this;
        }

        public Criteria andLoginKeyBetween(String value1, String value2) {
            addCriterion("login_key between", value1, value2, "loginKey");
            return (Criteria) this;
        }

        public Criteria andLoginKeyNotBetween(String value1, String value2) {
            addCriterion("login_key not between", value1, value2, "loginKey");
            return (Criteria) this;
        }

        public Criteria andLoginPassIsNull() {
            addCriterion("login_pass is null");
            return (Criteria) this;
        }

        public Criteria andLoginPassIsNotNull() {
            addCriterion("login_pass is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPassEqualTo(String value) {
            if (value != null) {
                addCriterion("login_pass =", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassNotEqualTo(String value) {
            if (value != null) {
                addCriterion("login_pass <>", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassGreaterThan(String value) {
            if (value != null) {
                addCriterion("login_pass >", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("login_pass >=", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassLessThan(String value) {
            if (value != null) {
                addCriterion("login_pass <", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("login_pass <=", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassLike(String value) {
            if (value != null) {
                addCriterion("login_pass like", "%"+value+"%", "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassNotLike(String value) {
            if (value != null) {
                addCriterion("login_pass not like", value, "loginPass");
            }
            return (Criteria) this;
        }

        public Criteria andLoginPassIn(List<String> values) {
            addCriterion("login_pass in", values, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassNotIn(List<String> values) {
            addCriterion("login_pass not in", values, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassBetween(String value1, String value2) {
            addCriterion("login_pass between", value1, value2, "loginPass");
            return (Criteria) this;
        }

        public Criteria andLoginPassNotBetween(String value1, String value2) {
            addCriterion("login_pass not between", value1, value2, "loginPass");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNull() {
            addCriterion("systemid is null");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNotNull() {
            addCriterion("systemid is not null");
            return (Criteria) this;
        }

        public Criteria andSystemidEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid =", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid <>", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("systemid >", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid >=", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidLessThan(Integer value) {
            if (value != null) {
                addCriterion("systemid <", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid <=", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidIn(List<Integer> values) {
            addCriterion("systemid in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotIn(List<Integer> values) {
            addCriterion("systemid not in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidBetween(Integer value1, Integer value2) {
            addCriterion("systemid between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotBetween(Integer value1, Integer value2) {
            addCriterion("systemid not between", value1, value2, "systemid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ll_supplier
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ll_supplier
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}