package com.yd.iotbusiness.mapper.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LmBillModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.billmonth
     *
     * @mbg.generated
     */
    private Integer billmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.cyclestartbalance
     *
     * @mbg.generated
     */
    private BigDecimal cyclestartbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.cycleendbalance
     *
     * @mbg.generated
     */
    private BigDecimal cycleendbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.cyclebuyamount
     *
     * @mbg.generated
     */
    private BigDecimal cyclebuyamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.quantity
     *
     * @mbg.generated
     */
    private BigDecimal quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.minconsumequantity
     *
     * @mbg.generated
     */
    private BigDecimal minconsumequantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.shouldwateramount
     *
     * @mbg.generated
     */
    private BigDecimal shouldwateramount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.minconsumamount
     *
     * @mbg.generated
     */
    private BigDecimal minconsumamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.additionalmount
     *
     * @mbg.generated
     */
    private BigDecimal additionalmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.realbillamount
     *
     * @mbg.generated
     */
    private BigDecimal realbillamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.waitpayrealbillamount
     *
     * @mbg.generated
     */
    private BigDecimal waitpayrealbillamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.waitpayrealwateramount
     *
     * @mbg.generated
     */
    private BigDecimal waitpayrealwateramount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.payamount
     *
     * @mbg.generated
     */
    private BigDecimal payamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.surchargeamount
     *
     * @mbg.generated
     */
    private BigDecimal surchargeamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.waitsurchargeamount
     *
     * @mbg.generated
     */
    private BigDecimal waitsurchargeamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.afterbalance
     *
     * @mbg.generated
     */
    private BigDecimal afterbalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.recentsurchargetime
     *
     * @mbg.generated
     */
    private Date recentsurchargetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.settletype
     *
     * @mbg.generated
     */
    private Byte settletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.factorycode
     *
     * @mbg.generated
     */
    private String factorycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.lifecode
     *
     * @mbg.generated
     */
    private Integer lifecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.meterid
     *
     * @mbg.generated
     */
    private Integer meterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.systemid
     *
     * @mbg.generated
     */
    private Integer systemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.settleid
     *
     * @mbg.generated
     */
    private Integer settleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.priceid
     *
     * @mbg.generated
     */
    private Integer priceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.billtype
     *
     * @mbg.generated
     */
    private Byte billtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_bill.operName
     *
     * @mbg.generated
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_bill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.id
     *
     * @return the value of lm_bill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.id
     *
     * @param id the value for lm_bill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.billmonth
     *
     * @return the value of lm_bill.billmonth
     *
     * @mbg.generated
     */
    public Integer getBillmonth() {
        return billmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.billmonth
     *
     * @param billmonth the value for lm_bill.billmonth
     *
     * @mbg.generated
     */
    public void setBillmonth(Integer billmonth) {
        this.billmonth = billmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.cyclestartbalance
     *
     * @return the value of lm_bill.cyclestartbalance
     *
     * @mbg.generated
     */
    public BigDecimal getCyclestartbalance() {
        return cyclestartbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.cyclestartbalance
     *
     * @param cyclestartbalance the value for lm_bill.cyclestartbalance
     *
     * @mbg.generated
     */
    public void setCyclestartbalance(BigDecimal cyclestartbalance) {
        this.cyclestartbalance = cyclestartbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.cycleendbalance
     *
     * @return the value of lm_bill.cycleendbalance
     *
     * @mbg.generated
     */
    public BigDecimal getCycleendbalance() {
        return cycleendbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.cycleendbalance
     *
     * @param cycleendbalance the value for lm_bill.cycleendbalance
     *
     * @mbg.generated
     */
    public void setCycleendbalance(BigDecimal cycleendbalance) {
        this.cycleendbalance = cycleendbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.cyclebuyamount
     *
     * @return the value of lm_bill.cyclebuyamount
     *
     * @mbg.generated
     */
    public BigDecimal getCyclebuyamount() {
        return cyclebuyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.cyclebuyamount
     *
     * @param cyclebuyamount the value for lm_bill.cyclebuyamount
     *
     * @mbg.generated
     */
    public void setCyclebuyamount(BigDecimal cyclebuyamount) {
        this.cyclebuyamount = cyclebuyamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.quantity
     *
     * @return the value of lm_bill.quantity
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.quantity
     *
     * @param quantity the value for lm_bill.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.minconsumequantity
     *
     * @return the value of lm_bill.minconsumequantity
     *
     * @mbg.generated
     */
    public BigDecimal getMinconsumequantity() {
        return minconsumequantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.minconsumequantity
     *
     * @param minconsumequantity the value for lm_bill.minconsumequantity
     *
     * @mbg.generated
     */
    public void setMinconsumequantity(BigDecimal minconsumequantity) {
        this.minconsumequantity = minconsumequantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.shouldwateramount
     *
     * @return the value of lm_bill.shouldwateramount
     *
     * @mbg.generated
     */
    public BigDecimal getShouldwateramount() {
        return shouldwateramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.shouldwateramount
     *
     * @param shouldwateramount the value for lm_bill.shouldwateramount
     *
     * @mbg.generated
     */
    public void setShouldwateramount(BigDecimal shouldwateramount) {
        this.shouldwateramount = shouldwateramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.minconsumamount
     *
     * @return the value of lm_bill.minconsumamount
     *
     * @mbg.generated
     */
    public BigDecimal getMinconsumamount() {
        return minconsumamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.minconsumamount
     *
     * @param minconsumamount the value for lm_bill.minconsumamount
     *
     * @mbg.generated
     */
    public void setMinconsumamount(BigDecimal minconsumamount) {
        this.minconsumamount = minconsumamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.additionalmount
     *
     * @return the value of lm_bill.additionalmount
     *
     * @mbg.generated
     */
    public BigDecimal getAdditionalmount() {
        return additionalmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.additionalmount
     *
     * @param additionalmount the value for lm_bill.additionalmount
     *
     * @mbg.generated
     */
    public void setAdditionalmount(BigDecimal additionalmount) {
        this.additionalmount = additionalmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.realbillamount
     *
     * @return the value of lm_bill.realbillamount
     *
     * @mbg.generated
     */
    public BigDecimal getRealbillamount() {
        return realbillamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.realbillamount
     *
     * @param realbillamount the value for lm_bill.realbillamount
     *
     * @mbg.generated
     */
    public void setRealbillamount(BigDecimal realbillamount) {
        this.realbillamount = realbillamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.waitpayrealbillamount
     *
     * @return the value of lm_bill.waitpayrealbillamount
     *
     * @mbg.generated
     */
    public BigDecimal getWaitpayrealbillamount() {
        return waitpayrealbillamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.waitpayrealbillamount
     *
     * @param waitpayrealbillamount the value for lm_bill.waitpayrealbillamount
     *
     * @mbg.generated
     */
    public void setWaitpayrealbillamount(BigDecimal waitpayrealbillamount) {
        this.waitpayrealbillamount = waitpayrealbillamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.waitpayrealwateramount
     *
     * @return the value of lm_bill.waitpayrealwateramount
     *
     * @mbg.generated
     */
    public BigDecimal getWaitpayrealwateramount() {
        return waitpayrealwateramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.waitpayrealwateramount
     *
     * @param waitpayrealwateramount the value for lm_bill.waitpayrealwateramount
     *
     * @mbg.generated
     */
    public void setWaitpayrealwateramount(BigDecimal waitpayrealwateramount) {
        this.waitpayrealwateramount = waitpayrealwateramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.payamount
     *
     * @return the value of lm_bill.payamount
     *
     * @mbg.generated
     */
    public BigDecimal getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.payamount
     *
     * @param payamount the value for lm_bill.payamount
     *
     * @mbg.generated
     */
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.surchargeamount
     *
     * @return the value of lm_bill.surchargeamount
     *
     * @mbg.generated
     */
    public BigDecimal getSurchargeamount() {
        return surchargeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.surchargeamount
     *
     * @param surchargeamount the value for lm_bill.surchargeamount
     *
     * @mbg.generated
     */
    public void setSurchargeamount(BigDecimal surchargeamount) {
        this.surchargeamount = surchargeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.waitsurchargeamount
     *
     * @return the value of lm_bill.waitsurchargeamount
     *
     * @mbg.generated
     */
    public BigDecimal getWaitsurchargeamount() {
        return waitsurchargeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.waitsurchargeamount
     *
     * @param waitsurchargeamount the value for lm_bill.waitsurchargeamount
     *
     * @mbg.generated
     */
    public void setWaitsurchargeamount(BigDecimal waitsurchargeamount) {
        this.waitsurchargeamount = waitsurchargeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.afterbalance
     *
     * @return the value of lm_bill.afterbalance
     *
     * @mbg.generated
     */
    public BigDecimal getAfterbalance() {
        return afterbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.afterbalance
     *
     * @param afterbalance the value for lm_bill.afterbalance
     *
     * @mbg.generated
     */
    public void setAfterbalance(BigDecimal afterbalance) {
        this.afterbalance = afterbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.createtime
     *
     * @return the value of lm_bill.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.createtime
     *
     * @param createtime the value for lm_bill.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.recentsurchargetime
     *
     * @return the value of lm_bill.recentsurchargetime
     *
     * @mbg.generated
     */
    public Date getRecentsurchargetime() {
        return recentsurchargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.recentsurchargetime
     *
     * @param recentsurchargetime the value for lm_bill.recentsurchargetime
     *
     * @mbg.generated
     */
    public void setRecentsurchargetime(Date recentsurchargetime) {
        this.recentsurchargetime = recentsurchargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.state
     *
     * @return the value of lm_bill.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.state
     *
     * @param state the value for lm_bill.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.settletype
     *
     * @return the value of lm_bill.settletype
     *
     * @mbg.generated
     */
    public Byte getSettletype() {
        return settletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.settletype
     *
     * @param settletype the value for lm_bill.settletype
     *
     * @mbg.generated
     */
    public void setSettletype(Byte settletype) {
        this.settletype = settletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.factorycode
     *
     * @return the value of lm_bill.factorycode
     *
     * @mbg.generated
     */
    public String getFactorycode() {
        return factorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.factorycode
     *
     * @param factorycode the value for lm_bill.factorycode
     *
     * @mbg.generated
     */
    public void setFactorycode(String factorycode) {
        this.factorycode = factorycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.lifecode
     *
     * @return the value of lm_bill.lifecode
     *
     * @mbg.generated
     */
    public Integer getLifecode() {
        return lifecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.lifecode
     *
     * @param lifecode the value for lm_bill.lifecode
     *
     * @mbg.generated
     */
    public void setLifecode(Integer lifecode) {
        this.lifecode = lifecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.meterid
     *
     * @return the value of lm_bill.meterid
     *
     * @mbg.generated
     */
    public Integer getMeterid() {
        return meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.meterid
     *
     * @param meterid the value for lm_bill.meterid
     *
     * @mbg.generated
     */
    public void setMeterid(Integer meterid) {
        this.meterid = meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.userid
     *
     * @return the value of lm_bill.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.userid
     *
     * @param userid the value for lm_bill.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.systemid
     *
     * @return the value of lm_bill.systemid
     *
     * @mbg.generated
     */
    public Integer getSystemid() {
        return systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.systemid
     *
     * @param systemid the value for lm_bill.systemid
     *
     * @mbg.generated
     */
    public void setSystemid(Integer systemid) {
        this.systemid = systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.settleid
     *
     * @return the value of lm_bill.settleid
     *
     * @mbg.generated
     */
    public Integer getSettleid() {
        return settleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.settleid
     *
     * @param settleid the value for lm_bill.settleid
     *
     * @mbg.generated
     */
    public void setSettleid(Integer settleid) {
        this.settleid = settleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.priceid
     *
     * @return the value of lm_bill.priceid
     *
     * @mbg.generated
     */
    public Integer getPriceid() {
        return priceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.priceid
     *
     * @param priceid the value for lm_bill.priceid
     *
     * @mbg.generated
     */
    public void setPriceid(Integer priceid) {
        this.priceid = priceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.billtype
     *
     * @return the value of lm_bill.billtype
     *
     * @mbg.generated
     */
    public Byte getBilltype() {
        return billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.billtype
     *
     * @param billtype the value for lm_bill.billtype
     *
     * @mbg.generated
     */
    public void setBilltype(Byte billtype) {
        this.billtype = billtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_bill.operName
     *
     * @return the value of lm_bill.operName
     *
     * @mbg.generated
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_bill.operName
     *
     * @param opername the value for lm_bill.operName
     *
     * @mbg.generated
     */
    public void setOpername(String opername) {
        this.opername = opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_bill
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", billmonth=").append(billmonth);
        sb.append(", cyclestartbalance=").append(cyclestartbalance);
        sb.append(", cycleendbalance=").append(cycleendbalance);
        sb.append(", cyclebuyamount=").append(cyclebuyamount);
        sb.append(", quantity=").append(quantity);
        sb.append(", minconsumequantity=").append(minconsumequantity);
        sb.append(", shouldwateramount=").append(shouldwateramount);
        sb.append(", minconsumamount=").append(minconsumamount);
        sb.append(", additionalmount=").append(additionalmount);
        sb.append(", realbillamount=").append(realbillamount);
        sb.append(", waitpayrealbillamount=").append(waitpayrealbillamount);
        sb.append(", waitpayrealwateramount=").append(waitpayrealwateramount);
        sb.append(", payamount=").append(payamount);
        sb.append(", surchargeamount=").append(surchargeamount);
        sb.append(", waitsurchargeamount=").append(waitsurchargeamount);
        sb.append(", afterbalance=").append(afterbalance);
        sb.append(", createtime=").append(createtime);
        sb.append(", recentsurchargetime=").append(recentsurchargetime);
        sb.append(", state=").append(state);
        sb.append(", settletype=").append(settletype);
        sb.append(", factorycode=").append(factorycode);
        sb.append(", lifecode=").append(lifecode);
        sb.append(", meterid=").append(meterid);
        sb.append(", userid=").append(userid);
        sb.append(", systemid=").append(systemid);
        sb.append(", settleid=").append(settleid);
        sb.append(", priceid=").append(priceid);
        sb.append(", billtype=").append(billtype);
        sb.append(", opername=").append(opername);
        sb.append("]");
        return sb.toString();
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }
}