package com.yd.iotbusiness.mapper.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LmCmdModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public LmCmdModelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }

    public LmCmdModelExample(Object pageInation) {
        oredCriteria = new ArrayList<>();
        LmCmdModel model = (LmCmdModel)pageInation;
        this.setPage(model.getPage());
        this.setRows(model.getRows());
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id =", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <>", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("id >", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id >=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            if (value != null) {
                addCriterion("id <", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCommtypeIsNull() {
            addCriterion("commtype is null");
            return (Criteria) this;
        }

        public Criteria andCommtypeIsNotNull() {
            addCriterion("commtype is not null");
            return (Criteria) this;
        }

        public Criteria andCommtypeEqualTo(Byte value) {
            if (value != null) {
                addCriterion("commtype =", value, "commtype");
            }
            return (Criteria) this;
        }

        public Criteria andCommtypeNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("commtype <>", value, "commtype");
            }
            return (Criteria) this;
        }

        public Criteria andCommtypeGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("commtype >", value, "commtype");
            }
            return (Criteria) this;
        }

        public Criteria andCommtypeGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("commtype >=", value, "commtype");
            }
            return (Criteria) this;
        }

        public Criteria andCommtypeLessThan(Byte value) {
            if (value != null) {
                addCriterion("commtype <", value, "commtype");
            }
            return (Criteria) this;
        }

        public Criteria andCommtypeLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("commtype <=", value, "commtype");
            }
            return (Criteria) this;
        }

        public Criteria andCommtypeIn(List<Byte> values) {
            addCriterion("commtype in", values, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeNotIn(List<Byte> values) {
            addCriterion("commtype not in", values, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeBetween(Byte value1, Byte value2) {
            addCriterion("commtype between", value1, value2, "commtype");
            return (Criteria) this;
        }

        public Criteria andCommtypeNotBetween(Byte value1, Byte value2) {
            addCriterion("commtype not between", value1, value2, "commtype");
            return (Criteria) this;
        }

        public Criteria andCentercodeIsNull() {
            addCriterion("centercode is null");
            return (Criteria) this;
        }

        public Criteria andCentercodeIsNotNull() {
            addCriterion("centercode is not null");
            return (Criteria) this;
        }

        public Criteria andCentercodeEqualTo(String value) {
            if (value != null) {
                addCriterion("centercode =", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("centercode <>", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeGreaterThan(String value) {
            if (value != null) {
                addCriterion("centercode >", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("centercode >=", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeLessThan(String value) {
            if (value != null) {
                addCriterion("centercode <", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("centercode <=", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeLike(String value) {
            if (value != null) {
                addCriterion("centercode like", "%"+value+"%", "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeNotLike(String value) {
            if (value != null) {
                addCriterion("centercode not like", value, "centercode");
            }
            return (Criteria) this;
        }

        public Criteria andCentercodeIn(List<String> values) {
            addCriterion("centercode in", values, "centercode");
            return (Criteria) this;
        }

        public Criteria andCentercodeNotIn(List<String> values) {
            addCriterion("centercode not in", values, "centercode");
            return (Criteria) this;
        }

        public Criteria andCentercodeBetween(String value1, String value2) {
            addCriterion("centercode between", value1, value2, "centercode");
            return (Criteria) this;
        }

        public Criteria andCentercodeNotBetween(String value1, String value2) {
            addCriterion("centercode not between", value1, value2, "centercode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeIsNull() {
            addCriterion("channelcode is null");
            return (Criteria) this;
        }

        public Criteria andChannelcodeIsNotNull() {
            addCriterion("channelcode is not null");
            return (Criteria) this;
        }

        public Criteria andChannelcodeEqualTo(Byte value) {
            if (value != null) {
                addCriterion("channelcode =", value, "channelcode");
            }
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("channelcode <>", value, "channelcode");
            }
            return (Criteria) this;
        }

        public Criteria andChannelcodeGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("channelcode >", value, "channelcode");
            }
            return (Criteria) this;
        }

        public Criteria andChannelcodeGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("channelcode >=", value, "channelcode");
            }
            return (Criteria) this;
        }

        public Criteria andChannelcodeLessThan(Byte value) {
            if (value != null) {
                addCriterion("channelcode <", value, "channelcode");
            }
            return (Criteria) this;
        }

        public Criteria andChannelcodeLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("channelcode <=", value, "channelcode");
            }
            return (Criteria) this;
        }

        public Criteria andChannelcodeIn(List<Byte> values) {
            addCriterion("channelcode in", values, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotIn(List<Byte> values) {
            addCriterion("channelcode not in", values, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeBetween(Byte value1, Byte value2) {
            addCriterion("channelcode between", value1, value2, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotBetween(Byte value1, Byte value2) {
            addCriterion("channelcode not between", value1, value2, "channelcode");
            return (Criteria) this;
        }

        public Criteria andMetercodeIsNull() {
            addCriterion("metercode is null");
            return (Criteria) this;
        }

        public Criteria andMetercodeIsNotNull() {
            addCriterion("metercode is not null");
            return (Criteria) this;
        }

        public Criteria andMetercodeEqualTo(String value) {
            if (value != null) {
                addCriterion("metercode =", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("metercode <>", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeGreaterThan(String value) {
            if (value != null) {
                addCriterion("metercode >", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("metercode >=", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeLessThan(String value) {
            if (value != null) {
                addCriterion("metercode <", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("metercode <=", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeLike(String value) {
            if (value != null) {
                addCriterion("metercode like", "%"+value+"%", "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeNotLike(String value) {
            if (value != null) {
                addCriterion("metercode not like", value, "metercode");
            }
            return (Criteria) this;
        }

        public Criteria andMetercodeIn(List<String> values) {
            addCriterion("metercode in", values, "metercode");
            return (Criteria) this;
        }

        public Criteria andMetercodeNotIn(List<String> values) {
            addCriterion("metercode not in", values, "metercode");
            return (Criteria) this;
        }

        public Criteria andMetercodeBetween(String value1, String value2) {
            addCriterion("metercode between", value1, value2, "metercode");
            return (Criteria) this;
        }

        public Criteria andMetercodeNotBetween(String value1, String value2) {
            addCriterion("metercode not between", value1, value2, "metercode");
            return (Criteria) this;
        }

        public Criteria andFactorycodeIsNull() {
            addCriterion("factorycode is null");
            return (Criteria) this;
        }

        public Criteria andFactorycodeIsNotNull() {
            addCriterion("factorycode is not null");
            return (Criteria) this;
        }

        public Criteria andFactorycodeEqualTo(String value) {
            if (value != null) {
                addCriterion("factorycode =", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("factorycode <>", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeGreaterThan(String value) {
            if (value != null) {
                addCriterion("factorycode >", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("factorycode >=", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeLessThan(String value) {
            if (value != null) {
                addCriterion("factorycode <", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("factorycode <=", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeLike(String value) {
            if (value != null) {
                addCriterion("factorycode like", "%"+value+"%", "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeNotLike(String value) {
            if (value != null) {
                addCriterion("factorycode not like", value, "factorycode");
            }
            return (Criteria) this;
        }

        public Criteria andFactorycodeIn(List<String> values) {
            addCriterion("factorycode in", values, "factorycode");
            return (Criteria) this;
        }

        public Criteria andFactorycodeNotIn(List<String> values) {
            addCriterion("factorycode not in", values, "factorycode");
            return (Criteria) this;
        }

        public Criteria andFactorycodeBetween(String value1, String value2) {
            addCriterion("factorycode between", value1, value2, "factorycode");
            return (Criteria) this;
        }

        public Criteria andFactorycodeNotBetween(String value1, String value2) {
            addCriterion("factorycode not between", value1, value2, "factorycode");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            if (value != null) {
                addCriterion("`state` =", value, "state");
            }
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("`state` <>", value, "state");
            }
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("`state` >", value, "state");
            }
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("`state` >=", value, "state");
            }
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            if (value != null) {
                addCriterion("`state` <", value, "state");
            }
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("`state` <=", value, "state");
            }
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            if (value != null) {
                addCriterion("`type` =", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("`type` <>", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            if (value != null) {
                addCriterion("`type` >", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`type` >=", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            if (value != null) {
                addCriterion("`type` <", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`type` <=", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            if (value != null) {
                addCriterion("`type` like", "%"+value+"%", "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            if (value != null) {
                addCriterion("`type` not like", value, "type");
            }
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime =", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime <>", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            if (value != null) {
                addCriterion("createtime >", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime >=", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            if (value != null) {
                addCriterion("createtime <", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime <=", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andExetimeIsNull() {
            addCriterion("exetime is null");
            return (Criteria) this;
        }

        public Criteria andExetimeIsNotNull() {
            addCriterion("exetime is not null");
            return (Criteria) this;
        }

        public Criteria andExetimeEqualTo(Date value) {
            if (value != null) {
                addCriterion("exetime =", value, "exetime");
            }
            return (Criteria) this;
        }

        public Criteria andExetimeNotEqualTo(Date value) {
            if (value != null) {
                addCriterion("exetime <>", value, "exetime");
            }
            return (Criteria) this;
        }

        public Criteria andExetimeGreaterThan(Date value) {
            if (value != null) {
                addCriterion("exetime >", value, "exetime");
            }
            return (Criteria) this;
        }

        public Criteria andExetimeGreaterThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("exetime >=", value, "exetime");
            }
            return (Criteria) this;
        }

        public Criteria andExetimeLessThan(Date value) {
            if (value != null) {
                addCriterion("exetime <", value, "exetime");
            }
            return (Criteria) this;
        }

        public Criteria andExetimeLessThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("exetime <=", value, "exetime");
            }
            return (Criteria) this;
        }

        public Criteria andExetimeIn(List<Date> values) {
            addCriterion("exetime in", values, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeNotIn(List<Date> values) {
            addCriterion("exetime not in", values, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeBetween(Date value1, Date value2) {
            addCriterion("exetime between", value1, value2, "exetime");
            return (Criteria) this;
        }

        public Criteria andExetimeNotBetween(Date value1, Date value2) {
            addCriterion("exetime not between", value1, value2, "exetime");
            return (Criteria) this;
        }

        public Criteria andTaskrepeatIsNull() {
            addCriterion("taskrepeat is null");
            return (Criteria) this;
        }

        public Criteria andTaskrepeatIsNotNull() {
            addCriterion("taskrepeat is not null");
            return (Criteria) this;
        }

        public Criteria andTaskrepeatEqualTo(Byte value) {
            if (value != null) {
                addCriterion("taskrepeat =", value, "taskrepeat");
            }
            return (Criteria) this;
        }

        public Criteria andTaskrepeatNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("taskrepeat <>", value, "taskrepeat");
            }
            return (Criteria) this;
        }

        public Criteria andTaskrepeatGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("taskrepeat >", value, "taskrepeat");
            }
            return (Criteria) this;
        }

        public Criteria andTaskrepeatGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("taskrepeat >=", value, "taskrepeat");
            }
            return (Criteria) this;
        }

        public Criteria andTaskrepeatLessThan(Byte value) {
            if (value != null) {
                addCriterion("taskrepeat <", value, "taskrepeat");
            }
            return (Criteria) this;
        }

        public Criteria andTaskrepeatLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("taskrepeat <=", value, "taskrepeat");
            }
            return (Criteria) this;
        }

        public Criteria andTaskrepeatIn(List<Byte> values) {
            addCriterion("taskrepeat in", values, "taskrepeat");
            return (Criteria) this;
        }

        public Criteria andTaskrepeatNotIn(List<Byte> values) {
            addCriterion("taskrepeat not in", values, "taskrepeat");
            return (Criteria) this;
        }

        public Criteria andTaskrepeatBetween(Byte value1, Byte value2) {
            addCriterion("taskrepeat between", value1, value2, "taskrepeat");
            return (Criteria) this;
        }

        public Criteria andTaskrepeatNotBetween(Byte value1, Byte value2) {
            addCriterion("taskrepeat not between", value1, value2, "taskrepeat");
            return (Criteria) this;
        }

        public Criteria andIspIsNull() {
            addCriterion("isp is null");
            return (Criteria) this;
        }

        public Criteria andIspIsNotNull() {
            addCriterion("isp is not null");
            return (Criteria) this;
        }

        public Criteria andIspEqualTo(Byte value) {
            if (value != null) {
                addCriterion("isp =", value, "isp");
            }
            return (Criteria) this;
        }

        public Criteria andIspNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("isp <>", value, "isp");
            }
            return (Criteria) this;
        }

        public Criteria andIspGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("isp >", value, "isp");
            }
            return (Criteria) this;
        }

        public Criteria andIspGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("isp >=", value, "isp");
            }
            return (Criteria) this;
        }

        public Criteria andIspLessThan(Byte value) {
            if (value != null) {
                addCriterion("isp <", value, "isp");
            }
            return (Criteria) this;
        }

        public Criteria andIspLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("isp <=", value, "isp");
            }
            return (Criteria) this;
        }

        public Criteria andIspIn(List<Byte> values) {
            addCriterion("isp in", values, "isp");
            return (Criteria) this;
        }

        public Criteria andIspNotIn(List<Byte> values) {
            addCriterion("isp not in", values, "isp");
            return (Criteria) this;
        }

        public Criteria andIspBetween(Byte value1, Byte value2) {
            addCriterion("isp between", value1, value2, "isp");
            return (Criteria) this;
        }

        public Criteria andIspNotBetween(Byte value1, Byte value2) {
            addCriterion("isp not between", value1, value2, "isp");
            return (Criteria) this;
        }

        public Criteria andIspidIsNull() {
            addCriterion("ispid is null");
            return (Criteria) this;
        }

        public Criteria andIspidIsNotNull() {
            addCriterion("ispid is not null");
            return (Criteria) this;
        }

        public Criteria andIspidEqualTo(String value) {
            if (value != null) {
                addCriterion("ispid =", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidNotEqualTo(String value) {
            if (value != null) {
                addCriterion("ispid <>", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidGreaterThan(String value) {
            if (value != null) {
                addCriterion("ispid >", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("ispid >=", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidLessThan(String value) {
            if (value != null) {
                addCriterion("ispid <", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("ispid <=", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidLike(String value) {
            if (value != null) {
                addCriterion("ispid like", "%"+value+"%", "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidNotLike(String value) {
            if (value != null) {
                addCriterion("ispid not like", value, "ispid");
            }
            return (Criteria) this;
        }

        public Criteria andIspidIn(List<String> values) {
            addCriterion("ispid in", values, "ispid");
            return (Criteria) this;
        }

        public Criteria andIspidNotIn(List<String> values) {
            addCriterion("ispid not in", values, "ispid");
            return (Criteria) this;
        }

        public Criteria andIspidBetween(String value1, String value2) {
            addCriterion("ispid between", value1, value2, "ispid");
            return (Criteria) this;
        }

        public Criteria andIspidNotBetween(String value1, String value2) {
            addCriterion("ispid not between", value1, value2, "ispid");
            return (Criteria) this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("imei is null");
            return (Criteria) this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("imei is not null");
            return (Criteria) this;
        }

        public Criteria andImeiEqualTo(String value) {
            if (value != null) {
                addCriterion("imei =", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            if (value != null) {
                addCriterion("imei <>", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThan(String value) {
            if (value != null) {
                addCriterion("imei >", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("imei >=", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiLessThan(String value) {
            if (value != null) {
                addCriterion("imei <", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("imei <=", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiLike(String value) {
            if (value != null) {
                addCriterion("imei like", "%"+value+"%", "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiNotLike(String value) {
            if (value != null) {
                addCriterion("imei not like", value, "imei");
            }
            return (Criteria) this;
        }

        public Criteria andImeiIn(List<String> values) {
            addCriterion("imei in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotIn(List<String> values) {
            addCriterion("imei not in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("imei between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("imei not between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andStationcodeIsNull() {
            addCriterion("stationcode is null");
            return (Criteria) this;
        }

        public Criteria andStationcodeIsNotNull() {
            addCriterion("stationcode is not null");
            return (Criteria) this;
        }

        public Criteria andStationcodeEqualTo(String value) {
            if (value != null) {
                addCriterion("stationcode =", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeNotEqualTo(String value) {
            if (value != null) {
                addCriterion("stationcode <>", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeGreaterThan(String value) {
            if (value != null) {
                addCriterion("stationcode >", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("stationcode >=", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeLessThan(String value) {
            if (value != null) {
                addCriterion("stationcode <", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("stationcode <=", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeLike(String value) {
            if (value != null) {
                addCriterion("stationcode like", "%"+value+"%", "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeNotLike(String value) {
            if (value != null) {
                addCriterion("stationcode not like", value, "stationcode");
            }
            return (Criteria) this;
        }

        public Criteria andStationcodeIn(List<String> values) {
            addCriterion("stationcode in", values, "stationcode");
            return (Criteria) this;
        }

        public Criteria andStationcodeNotIn(List<String> values) {
            addCriterion("stationcode not in", values, "stationcode");
            return (Criteria) this;
        }

        public Criteria andStationcodeBetween(String value1, String value2) {
            addCriterion("stationcode between", value1, value2, "stationcode");
            return (Criteria) this;
        }

        public Criteria andStationcodeNotBetween(String value1, String value2) {
            addCriterion("stationcode not between", value1, value2, "stationcode");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            if (value != null) {
                addCriterion("remark =", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            if (value != null) {
                addCriterion("remark <>", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            if (value != null) {
                addCriterion("remark >", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("remark >=", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            if (value != null) {
                addCriterion("remark <", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("remark <=", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            if (value != null) {
                addCriterion("remark like", "%"+value+"%", "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            if (value != null) {
                addCriterion("remark not like", value, "remark");
            }
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOperatornameIsNull() {
            addCriterion("operatorname is null");
            return (Criteria) this;
        }

        public Criteria andOperatornameIsNotNull() {
            addCriterion("operatorname is not null");
            return (Criteria) this;
        }

        public Criteria andOperatornameEqualTo(String value) {
            if (value != null) {
                addCriterion("operatorname =", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameNotEqualTo(String value) {
            if (value != null) {
                addCriterion("operatorname <>", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameGreaterThan(String value) {
            if (value != null) {
                addCriterion("operatorname >", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("operatorname >=", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameLessThan(String value) {
            if (value != null) {
                addCriterion("operatorname <", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("operatorname <=", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameLike(String value) {
            if (value != null) {
                addCriterion("operatorname like", "%"+value+"%", "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameNotLike(String value) {
            if (value != null) {
                addCriterion("operatorname not like", value, "operatorname");
            }
            return (Criteria) this;
        }

        public Criteria andOperatornameIn(List<String> values) {
            addCriterion("operatorname in", values, "operatorname");
            return (Criteria) this;
        }

        public Criteria andOperatornameNotIn(List<String> values) {
            addCriterion("operatorname not in", values, "operatorname");
            return (Criteria) this;
        }

        public Criteria andOperatornameBetween(String value1, String value2) {
            addCriterion("operatorname between", value1, value2, "operatorname");
            return (Criteria) this;
        }

        public Criteria andOperatornameNotBetween(String value1, String value2) {
            addCriterion("operatorname not between", value1, value2, "operatorname");
            return (Criteria) this;
        }

        public Criteria andValveIsNull() {
            addCriterion("valve is null");
            return (Criteria) this;
        }

        public Criteria andValveIsNotNull() {
            addCriterion("valve is not null");
            return (Criteria) this;
        }

        public Criteria andValveEqualTo(Byte value) {
            if (value != null) {
                addCriterion("valve =", value, "valve");
            }
            return (Criteria) this;
        }

        public Criteria andValveNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("valve <>", value, "valve");
            }
            return (Criteria) this;
        }

        public Criteria andValveGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("valve >", value, "valve");
            }
            return (Criteria) this;
        }

        public Criteria andValveGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("valve >=", value, "valve");
            }
            return (Criteria) this;
        }

        public Criteria andValveLessThan(Byte value) {
            if (value != null) {
                addCriterion("valve <", value, "valve");
            }
            return (Criteria) this;
        }

        public Criteria andValveLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("valve <=", value, "valve");
            }
            return (Criteria) this;
        }

        public Criteria andValveIn(List<Byte> values) {
            addCriterion("valve in", values, "valve");
            return (Criteria) this;
        }

        public Criteria andValveNotIn(List<Byte> values) {
            addCriterion("valve not in", values, "valve");
            return (Criteria) this;
        }

        public Criteria andValveBetween(Byte value1, Byte value2) {
            addCriterion("valve between", value1, value2, "valve");
            return (Criteria) this;
        }

        public Criteria andValveNotBetween(Byte value1, Byte value2) {
            addCriterion("valve not between", value1, value2, "valve");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNull() {
            addCriterion("systemid is null");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNotNull() {
            addCriterion("systemid is not null");
            return (Criteria) this;
        }

        public Criteria andSystemidEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid =", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid <>", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("systemid >", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid >=", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidLessThan(Integer value) {
            if (value != null) {
                addCriterion("systemid <", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid <=", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidIn(List<Integer> values) {
            addCriterion("systemid in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotIn(List<Integer> values) {
            addCriterion("systemid not in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidBetween(Integer value1, Integer value2) {
            addCriterion("systemid between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotBetween(Integer value1, Integer value2) {
            addCriterion("systemid not between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andProductidIsNull() {
            addCriterion("productid is null");
            return (Criteria) this;
        }

        public Criteria andProductidIsNotNull() {
            addCriterion("productid is not null");
            return (Criteria) this;
        }

        public Criteria andProductidEqualTo(Integer value) {
            if (value != null) {
                addCriterion("productid =", value, "productid");
            }
            return (Criteria) this;
        }

        public Criteria andProductidNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("productid <>", value, "productid");
            }
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("productid >", value, "productid");
            }
            return (Criteria) this;
        }

        public Criteria andProductidGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("productid >=", value, "productid");
            }
            return (Criteria) this;
        }

        public Criteria andProductidLessThan(Integer value) {
            if (value != null) {
                addCriterion("productid <", value, "productid");
            }
            return (Criteria) this;
        }

        public Criteria andProductidLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("productid <=", value, "productid");
            }
            return (Criteria) this;
        }

        public Criteria andProductidIn(List<Integer> values) {
            addCriterion("productid in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotIn(List<Integer> values) {
            addCriterion("productid not in", values, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidBetween(Integer value1, Integer value2) {
            addCriterion("productid between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andProductidNotBetween(Integer value1, Integer value2) {
            addCriterion("productid not between", value1, value2, "productid");
            return (Criteria) this;
        }

        public Criteria andCenteridIsNull() {
            addCriterion("centerid is null");
            return (Criteria) this;
        }

        public Criteria andCenteridIsNotNull() {
            addCriterion("centerid is not null");
            return (Criteria) this;
        }

        public Criteria andCenteridEqualTo(Integer value) {
            if (value != null) {
                addCriterion("centerid =", value, "centerid");
            }
            return (Criteria) this;
        }

        public Criteria andCenteridNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("centerid <>", value, "centerid");
            }
            return (Criteria) this;
        }

        public Criteria andCenteridGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("centerid >", value, "centerid");
            }
            return (Criteria) this;
        }

        public Criteria andCenteridGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("centerid >=", value, "centerid");
            }
            return (Criteria) this;
        }

        public Criteria andCenteridLessThan(Integer value) {
            if (value != null) {
                addCriterion("centerid <", value, "centerid");
            }
            return (Criteria) this;
        }

        public Criteria andCenteridLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("centerid <=", value, "centerid");
            }
            return (Criteria) this;
        }

        public Criteria andCenteridIn(List<Integer> values) {
            addCriterion("centerid in", values, "centerid");
            return (Criteria) this;
        }

        public Criteria andCenteridNotIn(List<Integer> values) {
            addCriterion("centerid not in", values, "centerid");
            return (Criteria) this;
        }

        public Criteria andCenteridBetween(Integer value1, Integer value2) {
            addCriterion("centerid between", value1, value2, "centerid");
            return (Criteria) this;
        }

        public Criteria andCenteridNotBetween(Integer value1, Integer value2) {
            addCriterion("centerid not between", value1, value2, "centerid");
            return (Criteria) this;
        }

        public Criteria andMeteridIsNull() {
            addCriterion("meterid is null");
            return (Criteria) this;
        }

        public Criteria andMeteridIsNotNull() {
            addCriterion("meterid is not null");
            return (Criteria) this;
        }

        public Criteria andMeteridEqualTo(Integer value) {
            if (value != null) {
                addCriterion("meterid =", value, "meterid");
            }
            return (Criteria) this;
        }

        public Criteria andMeteridNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("meterid <>", value, "meterid");
            }
            return (Criteria) this;
        }

        public Criteria andMeteridGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("meterid >", value, "meterid");
            }
            return (Criteria) this;
        }

        public Criteria andMeteridGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("meterid >=", value, "meterid");
            }
            return (Criteria) this;
        }

        public Criteria andMeteridLessThan(Integer value) {
            if (value != null) {
                addCriterion("meterid <", value, "meterid");
            }
            return (Criteria) this;
        }

        public Criteria andMeteridLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("meterid <=", value, "meterid");
            }
            return (Criteria) this;
        }

        public Criteria andMeteridIn(List<Integer> values) {
            addCriterion("meterid in", values, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridNotIn(List<Integer> values) {
            addCriterion("meterid not in", values, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridBetween(Integer value1, Integer value2) {
            addCriterion("meterid between", value1, value2, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridNotBetween(Integer value1, Integer value2) {
            addCriterion("meterid not between", value1, value2, "meterid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            if (value != null) {
                addCriterion("userid =", value, "userid");
            }
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("userid <>", value, "userid");
            }
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("userid >", value, "userid");
            }
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("userid >=", value, "userid");
            }
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            if (value != null) {
                addCriterion("userid <", value, "userid");
            }
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("userid <=", value, "userid");
            }
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andOperatoridIsNull() {
            addCriterion("operatorid is null");
            return (Criteria) this;
        }

        public Criteria andOperatoridIsNotNull() {
            addCriterion("operatorid is not null");
            return (Criteria) this;
        }

        public Criteria andOperatoridEqualTo(Integer value) {
            if (value != null) {
                addCriterion("operatorid =", value, "operatorid");
            }
            return (Criteria) this;
        }

        public Criteria andOperatoridNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("operatorid <>", value, "operatorid");
            }
            return (Criteria) this;
        }

        public Criteria andOperatoridGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("operatorid >", value, "operatorid");
            }
            return (Criteria) this;
        }

        public Criteria andOperatoridGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("operatorid >=", value, "operatorid");
            }
            return (Criteria) this;
        }

        public Criteria andOperatoridLessThan(Integer value) {
            if (value != null) {
                addCriterion("operatorid <", value, "operatorid");
            }
            return (Criteria) this;
        }

        public Criteria andOperatoridLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("operatorid <=", value, "operatorid");
            }
            return (Criteria) this;
        }

        public Criteria andOperatoridIn(List<Integer> values) {
            addCriterion("operatorid in", values, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotIn(List<Integer> values) {
            addCriterion("operatorid not in", values, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridBetween(Integer value1, Integer value2) {
            addCriterion("operatorid between", value1, value2, "operatorid");
            return (Criteria) this;
        }

        public Criteria andOperatoridNotBetween(Integer value1, Integer value2) {
            addCriterion("operatorid not between", value1, value2, "operatorid");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNull() {
            addCriterion("taskid is null");
            return (Criteria) this;
        }

        public Criteria andTaskidIsNotNull() {
            addCriterion("taskid is not null");
            return (Criteria) this;
        }

        public Criteria andTaskidEqualTo(String value) {
            if (value != null) {
                addCriterion("taskid =", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidNotEqualTo(String value) {
            if (value != null) {
                addCriterion("taskid <>", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThan(String value) {
            if (value != null) {
                addCriterion("taskid >", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("taskid >=", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidLessThan(String value) {
            if (value != null) {
                addCriterion("taskid <", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("taskid <=", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidLike(String value) {
            if (value != null) {
                addCriterion("taskid like", "%"+value+"%", "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidNotLike(String value) {
            if (value != null) {
                addCriterion("taskid not like", value, "taskid");
            }
            return (Criteria) this;
        }

        public Criteria andTaskidIn(List<String> values) {
            addCriterion("taskid in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotIn(List<String> values) {
            addCriterion("taskid not in", values, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidBetween(String value1, String value2) {
            addCriterion("taskid between", value1, value2, "taskid");
            return (Criteria) this;
        }

        public Criteria andTaskidNotBetween(String value1, String value2) {
            addCriterion("taskid not between", value1, value2, "taskid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_cmd
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_cmd
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}