package com.yd.iotbusiness.mapper.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LmPaymentModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.systemid
     *
     * @mbg.generated
     */
    private Integer systemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.wxorderid
     *
     * @mbg.generated
     */
    private String wxorderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.dealmode
     *
     * @mbg.generated
     */
    private Byte dealmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.paychannel
     *
     * @mbg.generated
     */
    private Byte paychannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.accountmode
     *
     * @mbg.generated
     */
    private Byte accountmode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.payamount
     *
     * @mbg.generated
     */
    private BigDecimal payamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.lossamount
     *
     * @mbg.generated
     */
    private BigDecimal lossamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.realamount
     *
     * @mbg.generated
     */
    private BigDecimal realamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.prebalance
     *
     * @mbg.generated
     */
    private BigDecimal prebalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.afterbalacne
     *
     * @mbg.generated
     */
    private BigDecimal afterbalacne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.userid
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.usercode
     *
     * @mbg.generated
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.useraddress
     *
     * @mbg.generated
     */
    private String useraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.meterid
     *
     * @mbg.generated
     */
    private Integer meterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.metercode
     *
     * @mbg.generated
     */
    private String metercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.lifecode
     *
     * @mbg.generated
     */
    private Integer lifecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.operatorid
     *
     * @mbg.generated
     */
    private Integer operatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.operatorname
     *
     * @mbg.generated
     */
    private String operatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.append
     *
     * @mbg.generated
     */
    private String append;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.paperflag
     *
     * @mbg.generated
     */
    private Byte paperflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.serialnum
     *
     * @mbg.generated
     */
    private String serialnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.paystate
     *
     * @mbg.generated
     */
    private Byte paystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.relatedid
     *
     * @mbg.generated
     */
    private Integer relatedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.writeamount
     *
     * @mbg.generated
     */
    private BigDecimal writeamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.writestate
     *
     * @mbg.generated
     */
    private Byte writestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.writeerrorcode
     *
     * @mbg.generated
     */
    private String writeerrorcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.quantity1
     *
     * @mbg.generated
     */
    private BigDecimal quantity1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.quantity2
     *
     * @mbg.generated
     */
    private BigDecimal quantity2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.quantity3
     *
     * @mbg.generated
     */
    private BigDecimal quantity3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.quantity4
     *
     * @mbg.generated
     */
    private BigDecimal quantity4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.quantity5
     *
     * @mbg.generated
     */
    private BigDecimal quantity5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.amount1
     *
     * @mbg.generated
     */
    private BigDecimal amount1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.amount2
     *
     * @mbg.generated
     */
    private BigDecimal amount2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.amount3
     *
     * @mbg.generated
     */
    private BigDecimal amount3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.amount4
     *
     * @mbg.generated
     */
    private BigDecimal amount4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.amount5
     *
     * @mbg.generated
     */
    private BigDecimal amount5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.waterfee
     *
     * @mbg.generated
     */
    private BigDecimal waterfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.sewagefee
     *
     * @mbg.generated
     */
    private BigDecimal sewagefee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.resourcefee
     *
     * @mbg.generated
     */
    private BigDecimal resourcefee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.adjustreason
     *
     * @mbg.generated
     */
    private String adjustreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.adjustnum
     *
     * @mbg.generated
     */
    private Integer adjustnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.marketcode
     *
     * @mbg.generated
     */
    private String marketcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.machineid
     *
     * @mbg.generated
     */
    private Integer machineid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.machineserialcode
     *
     * @mbg.generated
     */
    private String machineserialcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.saleremark
     *
     * @mbg.generated
     */
    private String saleremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.ladderinfo
     *
     * @mbg.generated
     */
    private String ladderinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.transseqnum
     *
     * @mbg.generated
     */
    private String transseqnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.merchantid
     *
     * @mbg.generated
     */
    private String merchantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.traceno
     *
     * @mbg.generated
     */
    private String traceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.sewagepaper
     *
     * @mbg.generated
     */
    private String sewagepaper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.meterpaper
     *
     * @mbg.generated
     */
    private String meterpaper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.meteramount
     *
     * @mbg.generated
     */
    private BigDecimal meteramount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.sewageamount
     *
     * @mbg.generated
     */
    private BigDecimal sewageamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.billid
     *
     * @mbg.generated
     */
    private Integer billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.servicecharge
     *
     * @mbg.generated
     */
    private BigDecimal servicecharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.fpdm
     *
     * @mbg.generated
     */
    private String fpdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.fphm
     *
     * @mbg.generated
     */
    private String fphm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.fpqqlsh
     *
     * @mbg.generated
     */
    private String fpqqlsh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.hjse
     *
     * @mbg.generated
     */
    private BigDecimal hjse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.bhsje
     *
     * @mbg.generated
     */
    private BigDecimal bhsje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.c_url
     *
     * @mbg.generated
     */
    private String cUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.tickettype
     *
     * @mbg.generated
     */
    private Integer tickettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.invoicestatus
     *
     * @mbg.generated
     */
    private Integer invoicestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.metertype
     *
     * @mbg.generated
     */
    private Byte metertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.pricename
     *
     * @mbg.generated
     */
    private String pricename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.pricecode
     *
     * @mbg.generated
     */
    private String pricecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.present
     *
     * @mbg.generated
     */
    private Byte present;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.marking
     *
     * @mbg.generated
     */
    private String marking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.timenocard
     *
     * @mbg.generated
     */
    private Integer timenocard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lm_payment.writed
     *
     * @mbg.generated
     */
    private Byte writed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_payment
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.id
     *
     * @return the value of lm_payment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.id
     *
     * @param id the value for lm_payment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.systemid
     *
     * @return the value of lm_payment.systemid
     *
     * @mbg.generated
     */
    public Integer getSystemid() {
        return systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.systemid
     *
     * @param systemid the value for lm_payment.systemid
     *
     * @mbg.generated
     */
    public void setSystemid(Integer systemid) {
        this.systemid = systemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.wxorderid
     *
     * @return the value of lm_payment.wxorderid
     *
     * @mbg.generated
     */
    public String getWxorderid() {
        return wxorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.wxorderid
     *
     * @param wxorderid the value for lm_payment.wxorderid
     *
     * @mbg.generated
     */
    public void setWxorderid(String wxorderid) {
        this.wxorderid = wxorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.dealmode
     *
     * @return the value of lm_payment.dealmode
     *
     * @mbg.generated
     */
    public Byte getDealmode() {
        return dealmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.dealmode
     *
     * @param dealmode the value for lm_payment.dealmode
     *
     * @mbg.generated
     */
    public void setDealmode(Byte dealmode) {
        this.dealmode = dealmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.paychannel
     *
     * @return the value of lm_payment.paychannel
     *
     * @mbg.generated
     */
    public Byte getPaychannel() {
        return paychannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.paychannel
     *
     * @param paychannel the value for lm_payment.paychannel
     *
     * @mbg.generated
     */
    public void setPaychannel(Byte paychannel) {
        this.paychannel = paychannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.accountmode
     *
     * @return the value of lm_payment.accountmode
     *
     * @mbg.generated
     */
    public Byte getAccountmode() {
        return accountmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.accountmode
     *
     * @param accountmode the value for lm_payment.accountmode
     *
     * @mbg.generated
     */
    public void setAccountmode(Byte accountmode) {
        this.accountmode = accountmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.amount
     *
     * @return the value of lm_payment.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.amount
     *
     * @param amount the value for lm_payment.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.payamount
     *
     * @return the value of lm_payment.payamount
     *
     * @mbg.generated
     */
    public BigDecimal getPayamount() {
        return payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.payamount
     *
     * @param payamount the value for lm_payment.payamount
     *
     * @mbg.generated
     */
    public void setPayamount(BigDecimal payamount) {
        this.payamount = payamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.lossamount
     *
     * @return the value of lm_payment.lossamount
     *
     * @mbg.generated
     */
    public BigDecimal getLossamount() {
        return lossamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.lossamount
     *
     * @param lossamount the value for lm_payment.lossamount
     *
     * @mbg.generated
     */
    public void setLossamount(BigDecimal lossamount) {
        this.lossamount = lossamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.realamount
     *
     * @return the value of lm_payment.realamount
     *
     * @mbg.generated
     */
    public BigDecimal getRealamount() {
        return realamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.realamount
     *
     * @param realamount the value for lm_payment.realamount
     *
     * @mbg.generated
     */
    public void setRealamount(BigDecimal realamount) {
        this.realamount = realamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.prebalance
     *
     * @return the value of lm_payment.prebalance
     *
     * @mbg.generated
     */
    public BigDecimal getPrebalance() {
        return prebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.prebalance
     *
     * @param prebalance the value for lm_payment.prebalance
     *
     * @mbg.generated
     */
    public void setPrebalance(BigDecimal prebalance) {
        this.prebalance = prebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.afterbalacne
     *
     * @return the value of lm_payment.afterbalacne
     *
     * @mbg.generated
     */
    public BigDecimal getAfterbalacne() {
        return afterbalacne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.afterbalacne
     *
     * @param afterbalacne the value for lm_payment.afterbalacne
     *
     * @mbg.generated
     */
    public void setAfterbalacne(BigDecimal afterbalacne) {
        this.afterbalacne = afterbalacne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.createtime
     *
     * @return the value of lm_payment.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.createtime
     *
     * @param createtime the value for lm_payment.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.userid
     *
     * @return the value of lm_payment.userid
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.userid
     *
     * @param userid the value for lm_payment.userid
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.usercode
     *
     * @return the value of lm_payment.usercode
     *
     * @mbg.generated
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.usercode
     *
     * @param usercode the value for lm_payment.usercode
     *
     * @mbg.generated
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.username
     *
     * @return the value of lm_payment.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.username
     *
     * @param username the value for lm_payment.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.useraddress
     *
     * @return the value of lm_payment.useraddress
     *
     * @mbg.generated
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.useraddress
     *
     * @param useraddress the value for lm_payment.useraddress
     *
     * @mbg.generated
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.meterid
     *
     * @return the value of lm_payment.meterid
     *
     * @mbg.generated
     */
    public Integer getMeterid() {
        return meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.meterid
     *
     * @param meterid the value for lm_payment.meterid
     *
     * @mbg.generated
     */
    public void setMeterid(Integer meterid) {
        this.meterid = meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.metercode
     *
     * @return the value of lm_payment.metercode
     *
     * @mbg.generated
     */
    public String getMetercode() {
        return metercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.metercode
     *
     * @param metercode the value for lm_payment.metercode
     *
     * @mbg.generated
     */
    public void setMetercode(String metercode) {
        this.metercode = metercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.lifecode
     *
     * @return the value of lm_payment.lifecode
     *
     * @mbg.generated
     */
    public Integer getLifecode() {
        return lifecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.lifecode
     *
     * @param lifecode the value for lm_payment.lifecode
     *
     * @mbg.generated
     */
    public void setLifecode(Integer lifecode) {
        this.lifecode = lifecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.operatorid
     *
     * @return the value of lm_payment.operatorid
     *
     * @mbg.generated
     */
    public Integer getOperatorid() {
        return operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.operatorid
     *
     * @param operatorid the value for lm_payment.operatorid
     *
     * @mbg.generated
     */
    public void setOperatorid(Integer operatorid) {
        this.operatorid = operatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.operatorname
     *
     * @return the value of lm_payment.operatorname
     *
     * @mbg.generated
     */
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.operatorname
     *
     * @param operatorname the value for lm_payment.operatorname
     *
     * @mbg.generated
     */
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.append
     *
     * @return the value of lm_payment.append
     *
     * @mbg.generated
     */
    public String getAppend() {
        return append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.append
     *
     * @param append the value for lm_payment.append
     *
     * @mbg.generated
     */
    public void setAppend(String append) {
        this.append = append;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.paperflag
     *
     * @return the value of lm_payment.paperflag
     *
     * @mbg.generated
     */
    public Byte getPaperflag() {
        return paperflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.paperflag
     *
     * @param paperflag the value for lm_payment.paperflag
     *
     * @mbg.generated
     */
    public void setPaperflag(Byte paperflag) {
        this.paperflag = paperflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.serialnum
     *
     * @return the value of lm_payment.serialnum
     *
     * @mbg.generated
     */
    public String getSerialnum() {
        return serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.serialnum
     *
     * @param serialnum the value for lm_payment.serialnum
     *
     * @mbg.generated
     */
    public void setSerialnum(String serialnum) {
        this.serialnum = serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.paystate
     *
     * @return the value of lm_payment.paystate
     *
     * @mbg.generated
     */
    public Byte getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.paystate
     *
     * @param paystate the value for lm_payment.paystate
     *
     * @mbg.generated
     */
    public void setPaystate(Byte paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.relatedid
     *
     * @return the value of lm_payment.relatedid
     *
     * @mbg.generated
     */
    public Integer getRelatedid() {
        return relatedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.relatedid
     *
     * @param relatedid the value for lm_payment.relatedid
     *
     * @mbg.generated
     */
    public void setRelatedid(Integer relatedid) {
        this.relatedid = relatedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.writeamount
     *
     * @return the value of lm_payment.writeamount
     *
     * @mbg.generated
     */
    public BigDecimal getWriteamount() {
        return writeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.writeamount
     *
     * @param writeamount the value for lm_payment.writeamount
     *
     * @mbg.generated
     */
    public void setWriteamount(BigDecimal writeamount) {
        this.writeamount = writeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.writestate
     *
     * @return the value of lm_payment.writestate
     *
     * @mbg.generated
     */
    public Byte getWritestate() {
        return writestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.writestate
     *
     * @param writestate the value for lm_payment.writestate
     *
     * @mbg.generated
     */
    public void setWritestate(Byte writestate) {
        this.writestate = writestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.writeerrorcode
     *
     * @return the value of lm_payment.writeerrorcode
     *
     * @mbg.generated
     */
    public String getWriteerrorcode() {
        return writeerrorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.writeerrorcode
     *
     * @param writeerrorcode the value for lm_payment.writeerrorcode
     *
     * @mbg.generated
     */
    public void setWriteerrorcode(String writeerrorcode) {
        this.writeerrorcode = writeerrorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.quantity1
     *
     * @return the value of lm_payment.quantity1
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity1() {
        return quantity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.quantity1
     *
     * @param quantity1 the value for lm_payment.quantity1
     *
     * @mbg.generated
     */
    public void setQuantity1(BigDecimal quantity1) {
        this.quantity1 = quantity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.quantity2
     *
     * @return the value of lm_payment.quantity2
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity2() {
        return quantity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.quantity2
     *
     * @param quantity2 the value for lm_payment.quantity2
     *
     * @mbg.generated
     */
    public void setQuantity2(BigDecimal quantity2) {
        this.quantity2 = quantity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.quantity3
     *
     * @return the value of lm_payment.quantity3
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity3() {
        return quantity3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.quantity3
     *
     * @param quantity3 the value for lm_payment.quantity3
     *
     * @mbg.generated
     */
    public void setQuantity3(BigDecimal quantity3) {
        this.quantity3 = quantity3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.quantity4
     *
     * @return the value of lm_payment.quantity4
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity4() {
        return quantity4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.quantity4
     *
     * @param quantity4 the value for lm_payment.quantity4
     *
     * @mbg.generated
     */
    public void setQuantity4(BigDecimal quantity4) {
        this.quantity4 = quantity4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.quantity5
     *
     * @return the value of lm_payment.quantity5
     *
     * @mbg.generated
     */
    public BigDecimal getQuantity5() {
        return quantity5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.quantity5
     *
     * @param quantity5 the value for lm_payment.quantity5
     *
     * @mbg.generated
     */
    public void setQuantity5(BigDecimal quantity5) {
        this.quantity5 = quantity5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.amount1
     *
     * @return the value of lm_payment.amount1
     *
     * @mbg.generated
     */
    public BigDecimal getAmount1() {
        return amount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.amount1
     *
     * @param amount1 the value for lm_payment.amount1
     *
     * @mbg.generated
     */
    public void setAmount1(BigDecimal amount1) {
        this.amount1 = amount1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.amount2
     *
     * @return the value of lm_payment.amount2
     *
     * @mbg.generated
     */
    public BigDecimal getAmount2() {
        return amount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.amount2
     *
     * @param amount2 the value for lm_payment.amount2
     *
     * @mbg.generated
     */
    public void setAmount2(BigDecimal amount2) {
        this.amount2 = amount2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.amount3
     *
     * @return the value of lm_payment.amount3
     *
     * @mbg.generated
     */
    public BigDecimal getAmount3() {
        return amount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.amount3
     *
     * @param amount3 the value for lm_payment.amount3
     *
     * @mbg.generated
     */
    public void setAmount3(BigDecimal amount3) {
        this.amount3 = amount3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.amount4
     *
     * @return the value of lm_payment.amount4
     *
     * @mbg.generated
     */
    public BigDecimal getAmount4() {
        return amount4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.amount4
     *
     * @param amount4 the value for lm_payment.amount4
     *
     * @mbg.generated
     */
    public void setAmount4(BigDecimal amount4) {
        this.amount4 = amount4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.amount5
     *
     * @return the value of lm_payment.amount5
     *
     * @mbg.generated
     */
    public BigDecimal getAmount5() {
        return amount5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.amount5
     *
     * @param amount5 the value for lm_payment.amount5
     *
     * @mbg.generated
     */
    public void setAmount5(BigDecimal amount5) {
        this.amount5 = amount5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.waterfee
     *
     * @return the value of lm_payment.waterfee
     *
     * @mbg.generated
     */
    public BigDecimal getWaterfee() {
        return waterfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.waterfee
     *
     * @param waterfee the value for lm_payment.waterfee
     *
     * @mbg.generated
     */
    public void setWaterfee(BigDecimal waterfee) {
        this.waterfee = waterfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.sewagefee
     *
     * @return the value of lm_payment.sewagefee
     *
     * @mbg.generated
     */
    public BigDecimal getSewagefee() {
        return sewagefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.sewagefee
     *
     * @param sewagefee the value for lm_payment.sewagefee
     *
     * @mbg.generated
     */
    public void setSewagefee(BigDecimal sewagefee) {
        this.sewagefee = sewagefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.resourcefee
     *
     * @return the value of lm_payment.resourcefee
     *
     * @mbg.generated
     */
    public BigDecimal getResourcefee() {
        return resourcefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.resourcefee
     *
     * @param resourcefee the value for lm_payment.resourcefee
     *
     * @mbg.generated
     */
    public void setResourcefee(BigDecimal resourcefee) {
        this.resourcefee = resourcefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.adjustreason
     *
     * @return the value of lm_payment.adjustreason
     *
     * @mbg.generated
     */
    public String getAdjustreason() {
        return adjustreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.adjustreason
     *
     * @param adjustreason the value for lm_payment.adjustreason
     *
     * @mbg.generated
     */
    public void setAdjustreason(String adjustreason) {
        this.adjustreason = adjustreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.adjustnum
     *
     * @return the value of lm_payment.adjustnum
     *
     * @mbg.generated
     */
    public Integer getAdjustnum() {
        return adjustnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.adjustnum
     *
     * @param adjustnum the value for lm_payment.adjustnum
     *
     * @mbg.generated
     */
    public void setAdjustnum(Integer adjustnum) {
        this.adjustnum = adjustnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.marketcode
     *
     * @return the value of lm_payment.marketcode
     *
     * @mbg.generated
     */
    public String getMarketcode() {
        return marketcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.marketcode
     *
     * @param marketcode the value for lm_payment.marketcode
     *
     * @mbg.generated
     */
    public void setMarketcode(String marketcode) {
        this.marketcode = marketcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.machineid
     *
     * @return the value of lm_payment.machineid
     *
     * @mbg.generated
     */
    public Integer getMachineid() {
        return machineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.machineid
     *
     * @param machineid the value for lm_payment.machineid
     *
     * @mbg.generated
     */
    public void setMachineid(Integer machineid) {
        this.machineid = machineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.machineserialcode
     *
     * @return the value of lm_payment.machineserialcode
     *
     * @mbg.generated
     */
    public String getMachineserialcode() {
        return machineserialcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.machineserialcode
     *
     * @param machineserialcode the value for lm_payment.machineserialcode
     *
     * @mbg.generated
     */
    public void setMachineserialcode(String machineserialcode) {
        this.machineserialcode = machineserialcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.saleremark
     *
     * @return the value of lm_payment.saleremark
     *
     * @mbg.generated
     */
    public String getSaleremark() {
        return saleremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.saleremark
     *
     * @param saleremark the value for lm_payment.saleremark
     *
     * @mbg.generated
     */
    public void setSaleremark(String saleremark) {
        this.saleremark = saleremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.ladderinfo
     *
     * @return the value of lm_payment.ladderinfo
     *
     * @mbg.generated
     */
    public String getLadderinfo() {
        return ladderinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.ladderinfo
     *
     * @param ladderinfo the value for lm_payment.ladderinfo
     *
     * @mbg.generated
     */
    public void setLadderinfo(String ladderinfo) {
        this.ladderinfo = ladderinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.transseqnum
     *
     * @return the value of lm_payment.transseqnum
     *
     * @mbg.generated
     */
    public String getTransseqnum() {
        return transseqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.transseqnum
     *
     * @param transseqnum the value for lm_payment.transseqnum
     *
     * @mbg.generated
     */
    public void setTransseqnum(String transseqnum) {
        this.transseqnum = transseqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.merchantid
     *
     * @return the value of lm_payment.merchantid
     *
     * @mbg.generated
     */
    public String getMerchantid() {
        return merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.merchantid
     *
     * @param merchantid the value for lm_payment.merchantid
     *
     * @mbg.generated
     */
    public void setMerchantid(String merchantid) {
        this.merchantid = merchantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.traceno
     *
     * @return the value of lm_payment.traceno
     *
     * @mbg.generated
     */
    public String getTraceno() {
        return traceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.traceno
     *
     * @param traceno the value for lm_payment.traceno
     *
     * @mbg.generated
     */
    public void setTraceno(String traceno) {
        this.traceno = traceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.sewagepaper
     *
     * @return the value of lm_payment.sewagepaper
     *
     * @mbg.generated
     */
    public String getSewagepaper() {
        return sewagepaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.sewagepaper
     *
     * @param sewagepaper the value for lm_payment.sewagepaper
     *
     * @mbg.generated
     */
    public void setSewagepaper(String sewagepaper) {
        this.sewagepaper = sewagepaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.meterpaper
     *
     * @return the value of lm_payment.meterpaper
     *
     * @mbg.generated
     */
    public String getMeterpaper() {
        return meterpaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.meterpaper
     *
     * @param meterpaper the value for lm_payment.meterpaper
     *
     * @mbg.generated
     */
    public void setMeterpaper(String meterpaper) {
        this.meterpaper = meterpaper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.meteramount
     *
     * @return the value of lm_payment.meteramount
     *
     * @mbg.generated
     */
    public BigDecimal getMeteramount() {
        return meteramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.meteramount
     *
     * @param meteramount the value for lm_payment.meteramount
     *
     * @mbg.generated
     */
    public void setMeteramount(BigDecimal meteramount) {
        this.meteramount = meteramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.sewageamount
     *
     * @return the value of lm_payment.sewageamount
     *
     * @mbg.generated
     */
    public BigDecimal getSewageamount() {
        return sewageamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.sewageamount
     *
     * @param sewageamount the value for lm_payment.sewageamount
     *
     * @mbg.generated
     */
    public void setSewageamount(BigDecimal sewageamount) {
        this.sewageamount = sewageamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.billid
     *
     * @return the value of lm_payment.billid
     *
     * @mbg.generated
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.billid
     *
     * @param billid the value for lm_payment.billid
     *
     * @mbg.generated
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.servicecharge
     *
     * @return the value of lm_payment.servicecharge
     *
     * @mbg.generated
     */
    public BigDecimal getServicecharge() {
        return servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.servicecharge
     *
     * @param servicecharge the value for lm_payment.servicecharge
     *
     * @mbg.generated
     */
    public void setServicecharge(BigDecimal servicecharge) {
        this.servicecharge = servicecharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.fpdm
     *
     * @return the value of lm_payment.fpdm
     *
     * @mbg.generated
     */
    public String getFpdm() {
        return fpdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.fpdm
     *
     * @param fpdm the value for lm_payment.fpdm
     *
     * @mbg.generated
     */
    public void setFpdm(String fpdm) {
        this.fpdm = fpdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.fphm
     *
     * @return the value of lm_payment.fphm
     *
     * @mbg.generated
     */
    public String getFphm() {
        return fphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.fphm
     *
     * @param fphm the value for lm_payment.fphm
     *
     * @mbg.generated
     */
    public void setFphm(String fphm) {
        this.fphm = fphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.fpqqlsh
     *
     * @return the value of lm_payment.fpqqlsh
     *
     * @mbg.generated
     */
    public String getFpqqlsh() {
        return fpqqlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.fpqqlsh
     *
     * @param fpqqlsh the value for lm_payment.fpqqlsh
     *
     * @mbg.generated
     */
    public void setFpqqlsh(String fpqqlsh) {
        this.fpqqlsh = fpqqlsh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.hjse
     *
     * @return the value of lm_payment.hjse
     *
     * @mbg.generated
     */
    public BigDecimal getHjse() {
        return hjse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.hjse
     *
     * @param hjse the value for lm_payment.hjse
     *
     * @mbg.generated
     */
    public void setHjse(BigDecimal hjse) {
        this.hjse = hjse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.bhsje
     *
     * @return the value of lm_payment.bhsje
     *
     * @mbg.generated
     */
    public BigDecimal getBhsje() {
        return bhsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.bhsje
     *
     * @param bhsje the value for lm_payment.bhsje
     *
     * @mbg.generated
     */
    public void setBhsje(BigDecimal bhsje) {
        this.bhsje = bhsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.c_url
     *
     * @return the value of lm_payment.c_url
     *
     * @mbg.generated
     */
    public String getcUrl() {
        return cUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.c_url
     *
     * @param cUrl the value for lm_payment.c_url
     *
     * @mbg.generated
     */
    public void setcUrl(String cUrl) {
        this.cUrl = cUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.tickettype
     *
     * @return the value of lm_payment.tickettype
     *
     * @mbg.generated
     */
    public Integer getTickettype() {
        return tickettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.tickettype
     *
     * @param tickettype the value for lm_payment.tickettype
     *
     * @mbg.generated
     */
    public void setTickettype(Integer tickettype) {
        this.tickettype = tickettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.invoicestatus
     *
     * @return the value of lm_payment.invoicestatus
     *
     * @mbg.generated
     */
    public Integer getInvoicestatus() {
        return invoicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.invoicestatus
     *
     * @param invoicestatus the value for lm_payment.invoicestatus
     *
     * @mbg.generated
     */
    public void setInvoicestatus(Integer invoicestatus) {
        this.invoicestatus = invoicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.metertype
     *
     * @return the value of lm_payment.metertype
     *
     * @mbg.generated
     */
    public Byte getMetertype() {
        return metertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.metertype
     *
     * @param metertype the value for lm_payment.metertype
     *
     * @mbg.generated
     */
    public void setMetertype(Byte metertype) {
        this.metertype = metertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.pricename
     *
     * @return the value of lm_payment.pricename
     *
     * @mbg.generated
     */
    public String getPricename() {
        return pricename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.pricename
     *
     * @param pricename the value for lm_payment.pricename
     *
     * @mbg.generated
     */
    public void setPricename(String pricename) {
        this.pricename = pricename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.pricecode
     *
     * @return the value of lm_payment.pricecode
     *
     * @mbg.generated
     */
    public String getPricecode() {
        return pricecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.pricecode
     *
     * @param pricecode the value for lm_payment.pricecode
     *
     * @mbg.generated
     */
    public void setPricecode(String pricecode) {
        this.pricecode = pricecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.present
     *
     * @return the value of lm_payment.present
     *
     * @mbg.generated
     */
    public Byte getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.present
     *
     * @param present the value for lm_payment.present
     *
     * @mbg.generated
     */
    public void setPresent(Byte present) {
        this.present = present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.marking
     *
     * @return the value of lm_payment.marking
     *
     * @mbg.generated
     */
    public String getMarking() {
        return marking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.marking
     *
     * @param marking the value for lm_payment.marking
     *
     * @mbg.generated
     */
    public void setMarking(String marking) {
        this.marking = marking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.timenocard
     *
     * @return the value of lm_payment.timenocard
     *
     * @mbg.generated
     */
    public Integer getTimenocard() {
        return timenocard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.timenocard
     *
     * @param timenocard the value for lm_payment.timenocard
     *
     * @mbg.generated
     */
    public void setTimenocard(Integer timenocard) {
        this.timenocard = timenocard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lm_payment.writed
     *
     * @return the value of lm_payment.writed
     *
     * @mbg.generated
     */
    public Byte getWrited() {
        return writed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lm_payment.writed
     *
     * @param writed the value for lm_payment.writed
     *
     * @mbg.generated
     */
    public void setWrited(Byte writed) {
        this.writed = writed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_payment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", systemid=").append(systemid);
        sb.append(", wxorderid=").append(wxorderid);
        sb.append(", dealmode=").append(dealmode);
        sb.append(", paychannel=").append(paychannel);
        sb.append(", accountmode=").append(accountmode);
        sb.append(", amount=").append(amount);
        sb.append(", payamount=").append(payamount);
        sb.append(", lossamount=").append(lossamount);
        sb.append(", realamount=").append(realamount);
        sb.append(", prebalance=").append(prebalance);
        sb.append(", afterbalacne=").append(afterbalacne);
        sb.append(", createtime=").append(createtime);
        sb.append(", userid=").append(userid);
        sb.append(", usercode=").append(usercode);
        sb.append(", username=").append(username);
        sb.append(", useraddress=").append(useraddress);
        sb.append(", meterid=").append(meterid);
        sb.append(", metercode=").append(metercode);
        sb.append(", lifecode=").append(lifecode);
        sb.append(", operatorid=").append(operatorid);
        sb.append(", operatorname=").append(operatorname);
        sb.append(", append=").append(append);
        sb.append(", paperflag=").append(paperflag);
        sb.append(", serialnum=").append(serialnum);
        sb.append(", paystate=").append(paystate);
        sb.append(", relatedid=").append(relatedid);
        sb.append(", writeamount=").append(writeamount);
        sb.append(", writestate=").append(writestate);
        sb.append(", writeerrorcode=").append(writeerrorcode);
        sb.append(", quantity1=").append(quantity1);
        sb.append(", quantity2=").append(quantity2);
        sb.append(", quantity3=").append(quantity3);
        sb.append(", quantity4=").append(quantity4);
        sb.append(", quantity5=").append(quantity5);
        sb.append(", amount1=").append(amount1);
        sb.append(", amount2=").append(amount2);
        sb.append(", amount3=").append(amount3);
        sb.append(", amount4=").append(amount4);
        sb.append(", amount5=").append(amount5);
        sb.append(", waterfee=").append(waterfee);
        sb.append(", sewagefee=").append(sewagefee);
        sb.append(", resourcefee=").append(resourcefee);
        sb.append(", adjustreason=").append(adjustreason);
        sb.append(", adjustnum=").append(adjustnum);
        sb.append(", marketcode=").append(marketcode);
        sb.append(", machineid=").append(machineid);
        sb.append(", machineserialcode=").append(machineserialcode);
        sb.append(", saleremark=").append(saleremark);
        sb.append(", ladderinfo=").append(ladderinfo);
        sb.append(", transseqnum=").append(transseqnum);
        sb.append(", merchantid=").append(merchantid);
        sb.append(", traceno=").append(traceno);
        sb.append(", sewagepaper=").append(sewagepaper);
        sb.append(", meterpaper=").append(meterpaper);
        sb.append(", meteramount=").append(meteramount);
        sb.append(", sewageamount=").append(sewageamount);
        sb.append(", billid=").append(billid);
        sb.append(", servicecharge=").append(servicecharge);
        sb.append(", fpdm=").append(fpdm);
        sb.append(", fphm=").append(fphm);
        sb.append(", fpqqlsh=").append(fpqqlsh);
        sb.append(", hjse=").append(hjse);
        sb.append(", bhsje=").append(bhsje);
        sb.append(", cUrl=").append(cUrl);
        sb.append(", tickettype=").append(tickettype);
        sb.append(", invoicestatus=").append(invoicestatus);
        sb.append(", metertype=").append(metertype);
        sb.append(", pricename=").append(pricename);
        sb.append(", pricecode=").append(pricecode);
        sb.append(", present=").append(present);
        sb.append(", marking=").append(marking);
        sb.append(", timenocard=").append(timenocard);
        sb.append(", writed=").append(writed);
        sb.append("]");
        return sb.toString();
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }
}