package com.yd.iotbusiness.mapper.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LmPriceModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    protected Integer rows;

    protected Integer page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public LmPriceModelExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    public Integer getRows() {
        return rows;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Integer getPage() {
        return page;
    }

    public LmPriceModelExample(Object pageInation) {
        oredCriteria = new ArrayList<>();
        LmPriceModel model = (LmPriceModel)pageInation;
        this.setPage(model.getPage());
        this.setRows(model.getRows());
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id =", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <>", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("id >", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id >=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            if (value != null) {
                addCriterion("id <", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("id <=", value, "id");
            }
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNull() {
            addCriterion("systemid is null");
            return (Criteria) this;
        }

        public Criteria andSystemidIsNotNull() {
            addCriterion("systemid is not null");
            return (Criteria) this;
        }

        public Criteria andSystemidEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid =", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid <>", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("systemid >", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid >=", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidLessThan(Integer value) {
            if (value != null) {
                addCriterion("systemid <", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("systemid <=", value, "systemid");
            }
            return (Criteria) this;
        }

        public Criteria andSystemidIn(List<Integer> values) {
            addCriterion("systemid in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotIn(List<Integer> values) {
            addCriterion("systemid not in", values, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidBetween(Integer value1, Integer value2) {
            addCriterion("systemid between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andSystemidNotBetween(Integer value1, Integer value2) {
            addCriterion("systemid not between", value1, value2, "systemid");
            return (Criteria) this;
        }

        public Criteria andSettleidIsNull() {
            addCriterion("settleid is null");
            return (Criteria) this;
        }

        public Criteria andSettleidIsNotNull() {
            addCriterion("settleid is not null");
            return (Criteria) this;
        }

        public Criteria andSettleidEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleid =", value, "settleid");
            }
            return (Criteria) this;
        }

        public Criteria andSettleidNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleid <>", value, "settleid");
            }
            return (Criteria) this;
        }

        public Criteria andSettleidGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("settleid >", value, "settleid");
            }
            return (Criteria) this;
        }

        public Criteria andSettleidGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleid >=", value, "settleid");
            }
            return (Criteria) this;
        }

        public Criteria andSettleidLessThan(Integer value) {
            if (value != null) {
                addCriterion("settleid <", value, "settleid");
            }
            return (Criteria) this;
        }

        public Criteria andSettleidLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleid <=", value, "settleid");
            }
            return (Criteria) this;
        }

        public Criteria andSettleidIn(List<Integer> values) {
            addCriterion("settleid in", values, "settleid");
            return (Criteria) this;
        }

        public Criteria andSettleidNotIn(List<Integer> values) {
            addCriterion("settleid not in", values, "settleid");
            return (Criteria) this;
        }

        public Criteria andSettleidBetween(Integer value1, Integer value2) {
            addCriterion("settleid between", value1, value2, "settleid");
            return (Criteria) this;
        }

        public Criteria andSettleidNotBetween(Integer value1, Integer value2) {
            addCriterion("settleid not between", value1, value2, "settleid");
            return (Criteria) this;
        }

        public Criteria andPaperidIsNull() {
            addCriterion("paperid is null");
            return (Criteria) this;
        }

        public Criteria andPaperidIsNotNull() {
            addCriterion("paperid is not null");
            return (Criteria) this;
        }

        public Criteria andPaperidEqualTo(Integer value) {
            if (value != null) {
                addCriterion("paperid =", value, "paperid");
            }
            return (Criteria) this;
        }

        public Criteria andPaperidNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("paperid <>", value, "paperid");
            }
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("paperid >", value, "paperid");
            }
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("paperid >=", value, "paperid");
            }
            return (Criteria) this;
        }

        public Criteria andPaperidLessThan(Integer value) {
            if (value != null) {
                addCriterion("paperid <", value, "paperid");
            }
            return (Criteria) this;
        }

        public Criteria andPaperidLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("paperid <=", value, "paperid");
            }
            return (Criteria) this;
        }

        public Criteria andPaperidIn(List<Integer> values) {
            addCriterion("paperid in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotIn(List<Integer> values) {
            addCriterion("paperid not in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidBetween(Integer value1, Integer value2) {
            addCriterion("paperid between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotBetween(Integer value1, Integer value2) {
            addCriterion("paperid not between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Integer value) {
            if (value != null) {
                addCriterion("code =", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("code <>", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("code >", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("code >=", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Integer value) {
            if (value != null) {
                addCriterion("code <", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("code <=", value, "code");
            }
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Integer> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Integer> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Integer value1, Integer value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` =", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` <>", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            if (value != null) {
                addCriterion("`name` >", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` >=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            if (value != null) {
                addCriterion("`name` <", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("`name` <=", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            if (value != null) {
                addCriterion("`name` like", "%"+value+"%", "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            if (value != null) {
                addCriterion("`name` not like", value, "name");
            }
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNull() {
            addCriterion("starttime is null");
            return (Criteria) this;
        }

        public Criteria andStarttimeIsNotNull() {
            addCriterion("starttime is not null");
            return (Criteria) this;
        }

        public Criteria andStarttimeEqualTo(Date value) {
            if (value != null) {
                addCriterion("starttime =", value, "starttime");
            }
            return (Criteria) this;
        }

        public Criteria andStarttimeNotEqualTo(Date value) {
            if (value != null) {
                addCriterion("starttime <>", value, "starttime");
            }
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThan(Date value) {
            if (value != null) {
                addCriterion("starttime >", value, "starttime");
            }
            return (Criteria) this;
        }

        public Criteria andStarttimeGreaterThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("starttime >=", value, "starttime");
            }
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThan(Date value) {
            if (value != null) {
                addCriterion("starttime <", value, "starttime");
            }
            return (Criteria) this;
        }

        public Criteria andStarttimeLessThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("starttime <=", value, "starttime");
            }
            return (Criteria) this;
        }

        public Criteria andStarttimeIn(List<Date> values) {
            addCriterion("starttime in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotIn(List<Date> values) {
            addCriterion("starttime not in", values, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeBetween(Date value1, Date value2) {
            addCriterion("starttime between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andStarttimeNotBetween(Date value1, Date value2) {
            addCriterion("starttime not between", value1, value2, "starttime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            if (value != null) {
                addCriterion("endtime =", value, "endtime");
            }
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            if (value != null) {
                addCriterion("endtime <>", value, "endtime");
            }
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            if (value != null) {
                addCriterion("endtime >", value, "endtime");
            }
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("endtime >=", value, "endtime");
            }
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            if (value != null) {
                addCriterion("endtime <", value, "endtime");
            }
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("endtime <=", value, "endtime");
            }
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andLaddertypeIsNull() {
            addCriterion("laddertype is null");
            return (Criteria) this;
        }

        public Criteria andLaddertypeIsNotNull() {
            addCriterion("laddertype is not null");
            return (Criteria) this;
        }

        public Criteria andLaddertypeEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddertype =", value, "laddertype");
            }
            return (Criteria) this;
        }

        public Criteria andLaddertypeNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddertype <>", value, "laddertype");
            }
            return (Criteria) this;
        }

        public Criteria andLaddertypeGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("laddertype >", value, "laddertype");
            }
            return (Criteria) this;
        }

        public Criteria andLaddertypeGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddertype >=", value, "laddertype");
            }
            return (Criteria) this;
        }

        public Criteria andLaddertypeLessThan(Byte value) {
            if (value != null) {
                addCriterion("laddertype <", value, "laddertype");
            }
            return (Criteria) this;
        }

        public Criteria andLaddertypeLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddertype <=", value, "laddertype");
            }
            return (Criteria) this;
        }

        public Criteria andLaddertypeIn(List<Byte> values) {
            addCriterion("laddertype in", values, "laddertype");
            return (Criteria) this;
        }

        public Criteria andLaddertypeNotIn(List<Byte> values) {
            addCriterion("laddertype not in", values, "laddertype");
            return (Criteria) this;
        }

        public Criteria andLaddertypeBetween(Byte value1, Byte value2) {
            addCriterion("laddertype between", value1, value2, "laddertype");
            return (Criteria) this;
        }

        public Criteria andLaddertypeNotBetween(Byte value1, Byte value2) {
            addCriterion("laddertype not between", value1, value2, "laddertype");
            return (Criteria) this;
        }

        public Criteria andLaddernumIsNull() {
            addCriterion("laddernum is null");
            return (Criteria) this;
        }

        public Criteria andLaddernumIsNotNull() {
            addCriterion("laddernum is not null");
            return (Criteria) this;
        }

        public Criteria andLaddernumEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddernum =", value, "laddernum");
            }
            return (Criteria) this;
        }

        public Criteria andLaddernumNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddernum <>", value, "laddernum");
            }
            return (Criteria) this;
        }

        public Criteria andLaddernumGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("laddernum >", value, "laddernum");
            }
            return (Criteria) this;
        }

        public Criteria andLaddernumGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddernum >=", value, "laddernum");
            }
            return (Criteria) this;
        }

        public Criteria andLaddernumLessThan(Byte value) {
            if (value != null) {
                addCriterion("laddernum <", value, "laddernum");
            }
            return (Criteria) this;
        }

        public Criteria andLaddernumLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("laddernum <=", value, "laddernum");
            }
            return (Criteria) this;
        }

        public Criteria andLaddernumIn(List<Byte> values) {
            addCriterion("laddernum in", values, "laddernum");
            return (Criteria) this;
        }

        public Criteria andLaddernumNotIn(List<Byte> values) {
            addCriterion("laddernum not in", values, "laddernum");
            return (Criteria) this;
        }

        public Criteria andLaddernumBetween(Byte value1, Byte value2) {
            addCriterion("laddernum between", value1, value2, "laddernum");
            return (Criteria) this;
        }

        public Criteria andLaddernumNotBetween(Byte value1, Byte value2) {
            addCriterion("laddernum not between", value1, value2, "laddernum");
            return (Criteria) this;
        }

        public Criteria andLadderaddupIsNull() {
            addCriterion("ladderaddup is null");
            return (Criteria) this;
        }

        public Criteria andLadderaddupIsNotNull() {
            addCriterion("ladderaddup is not null");
            return (Criteria) this;
        }

        public Criteria andLadderaddupEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("ladderaddup =", value, "ladderaddup");
            }
            return (Criteria) this;
        }

        public Criteria andLadderaddupNotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("ladderaddup <>", value, "ladderaddup");
            }
            return (Criteria) this;
        }

        public Criteria andLadderaddupGreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("ladderaddup >", value, "ladderaddup");
            }
            return (Criteria) this;
        }

        public Criteria andLadderaddupGreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("ladderaddup >=", value, "ladderaddup");
            }
            return (Criteria) this;
        }

        public Criteria andLadderaddupLessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("ladderaddup <", value, "ladderaddup");
            }
            return (Criteria) this;
        }

        public Criteria andLadderaddupLessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("ladderaddup <=", value, "ladderaddup");
            }
            return (Criteria) this;
        }

        public Criteria andLadderaddupIn(List<BigDecimal> values) {
            addCriterion("ladderaddup in", values, "ladderaddup");
            return (Criteria) this;
        }

        public Criteria andLadderaddupNotIn(List<BigDecimal> values) {
            addCriterion("ladderaddup not in", values, "ladderaddup");
            return (Criteria) this;
        }

        public Criteria andLadderaddupBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ladderaddup between", value1, value2, "ladderaddup");
            return (Criteria) this;
        }

        public Criteria andLadderaddupNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ladderaddup not between", value1, value2, "ladderaddup");
            return (Criteria) this;
        }

        public Criteria andPopulationIsNull() {
            addCriterion("population is null");
            return (Criteria) this;
        }

        public Criteria andPopulationIsNotNull() {
            addCriterion("population is not null");
            return (Criteria) this;
        }

        public Criteria andPopulationEqualTo(Byte value) {
            if (value != null) {
                addCriterion("population =", value, "population");
            }
            return (Criteria) this;
        }

        public Criteria andPopulationNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("population <>", value, "population");
            }
            return (Criteria) this;
        }

        public Criteria andPopulationGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("population >", value, "population");
            }
            return (Criteria) this;
        }

        public Criteria andPopulationGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("population >=", value, "population");
            }
            return (Criteria) this;
        }

        public Criteria andPopulationLessThan(Byte value) {
            if (value != null) {
                addCriterion("population <", value, "population");
            }
            return (Criteria) this;
        }

        public Criteria andPopulationLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("population <=", value, "population");
            }
            return (Criteria) this;
        }

        public Criteria andPopulationIn(List<Byte> values) {
            addCriterion("population in", values, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationNotIn(List<Byte> values) {
            addCriterion("population not in", values, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationBetween(Byte value1, Byte value2) {
            addCriterion("population between", value1, value2, "population");
            return (Criteria) this;
        }

        public Criteria andPopulationNotBetween(Byte value1, Byte value2) {
            addCriterion("population not between", value1, value2, "population");
            return (Criteria) this;
        }

        public Criteria andQuantity1IsNull() {
            addCriterion("quantity1 is null");
            return (Criteria) this;
        }

        public Criteria andQuantity1IsNotNull() {
            addCriterion("quantity1 is not null");
            return (Criteria) this;
        }

        public Criteria andQuantity1EqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity1 =", value, "quantity1");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity1NotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity1 <>", value, "quantity1");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity1GreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity1 >", value, "quantity1");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity1GreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity1 >=", value, "quantity1");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity1LessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity1 <", value, "quantity1");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity1LessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity1 <=", value, "quantity1");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity1In(List<BigDecimal> values) {
            addCriterion("quantity1 in", values, "quantity1");
            return (Criteria) this;
        }

        public Criteria andQuantity1NotIn(List<BigDecimal> values) {
            addCriterion("quantity1 not in", values, "quantity1");
            return (Criteria) this;
        }

        public Criteria andQuantity1Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity1 between", value1, value2, "quantity1");
            return (Criteria) this;
        }

        public Criteria andQuantity1NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity1 not between", value1, value2, "quantity1");
            return (Criteria) this;
        }

        public Criteria andQuantity2IsNull() {
            addCriterion("quantity2 is null");
            return (Criteria) this;
        }

        public Criteria andQuantity2IsNotNull() {
            addCriterion("quantity2 is not null");
            return (Criteria) this;
        }

        public Criteria andQuantity2EqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity2 =", value, "quantity2");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity2NotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity2 <>", value, "quantity2");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity2GreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity2 >", value, "quantity2");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity2GreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity2 >=", value, "quantity2");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity2LessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity2 <", value, "quantity2");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity2LessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity2 <=", value, "quantity2");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity2In(List<BigDecimal> values) {
            addCriterion("quantity2 in", values, "quantity2");
            return (Criteria) this;
        }

        public Criteria andQuantity2NotIn(List<BigDecimal> values) {
            addCriterion("quantity2 not in", values, "quantity2");
            return (Criteria) this;
        }

        public Criteria andQuantity2Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity2 between", value1, value2, "quantity2");
            return (Criteria) this;
        }

        public Criteria andQuantity2NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity2 not between", value1, value2, "quantity2");
            return (Criteria) this;
        }

        public Criteria andQuantity3IsNull() {
            addCriterion("quantity3 is null");
            return (Criteria) this;
        }

        public Criteria andQuantity3IsNotNull() {
            addCriterion("quantity3 is not null");
            return (Criteria) this;
        }

        public Criteria andQuantity3EqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity3 =", value, "quantity3");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity3NotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity3 <>", value, "quantity3");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity3GreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity3 >", value, "quantity3");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity3GreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity3 >=", value, "quantity3");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity3LessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity3 <", value, "quantity3");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity3LessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity3 <=", value, "quantity3");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity3In(List<BigDecimal> values) {
            addCriterion("quantity3 in", values, "quantity3");
            return (Criteria) this;
        }

        public Criteria andQuantity3NotIn(List<BigDecimal> values) {
            addCriterion("quantity3 not in", values, "quantity3");
            return (Criteria) this;
        }

        public Criteria andQuantity3Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity3 between", value1, value2, "quantity3");
            return (Criteria) this;
        }

        public Criteria andQuantity3NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity3 not between", value1, value2, "quantity3");
            return (Criteria) this;
        }

        public Criteria andQuantity4IsNull() {
            addCriterion("quantity4 is null");
            return (Criteria) this;
        }

        public Criteria andQuantity4IsNotNull() {
            addCriterion("quantity4 is not null");
            return (Criteria) this;
        }

        public Criteria andQuantity4EqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity4 =", value, "quantity4");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity4NotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity4 <>", value, "quantity4");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity4GreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity4 >", value, "quantity4");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity4GreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity4 >=", value, "quantity4");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity4LessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity4 <", value, "quantity4");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity4LessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity4 <=", value, "quantity4");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity4In(List<BigDecimal> values) {
            addCriterion("quantity4 in", values, "quantity4");
            return (Criteria) this;
        }

        public Criteria andQuantity4NotIn(List<BigDecimal> values) {
            addCriterion("quantity4 not in", values, "quantity4");
            return (Criteria) this;
        }

        public Criteria andQuantity4Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity4 between", value1, value2, "quantity4");
            return (Criteria) this;
        }

        public Criteria andQuantity4NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity4 not between", value1, value2, "quantity4");
            return (Criteria) this;
        }

        public Criteria andQuantity5IsNull() {
            addCriterion("quantity5 is null");
            return (Criteria) this;
        }

        public Criteria andQuantity5IsNotNull() {
            addCriterion("quantity5 is not null");
            return (Criteria) this;
        }

        public Criteria andQuantity5EqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity5 =", value, "quantity5");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity5NotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity5 <>", value, "quantity5");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity5GreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity5 >", value, "quantity5");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity5GreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity5 >=", value, "quantity5");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity5LessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity5 <", value, "quantity5");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity5LessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("quantity5 <=", value, "quantity5");
            }
            return (Criteria) this;
        }

        public Criteria andQuantity5In(List<BigDecimal> values) {
            addCriterion("quantity5 in", values, "quantity5");
            return (Criteria) this;
        }

        public Criteria andQuantity5NotIn(List<BigDecimal> values) {
            addCriterion("quantity5 not in", values, "quantity5");
            return (Criteria) this;
        }

        public Criteria andQuantity5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity5 between", value1, value2, "quantity5");
            return (Criteria) this;
        }

        public Criteria andQuantity5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("quantity5 not between", value1, value2, "quantity5");
            return (Criteria) this;
        }

        public Criteria andSettlemonthIsNull() {
            addCriterion("settlemonth is null");
            return (Criteria) this;
        }

        public Criteria andSettlemonthIsNotNull() {
            addCriterion("settlemonth is not null");
            return (Criteria) this;
        }

        public Criteria andSettlemonthEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settlemonth =", value, "settlemonth");
            }
            return (Criteria) this;
        }

        public Criteria andSettlemonthNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settlemonth <>", value, "settlemonth");
            }
            return (Criteria) this;
        }

        public Criteria andSettlemonthGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("settlemonth >", value, "settlemonth");
            }
            return (Criteria) this;
        }

        public Criteria andSettlemonthGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settlemonth >=", value, "settlemonth");
            }
            return (Criteria) this;
        }

        public Criteria andSettlemonthLessThan(Integer value) {
            if (value != null) {
                addCriterion("settlemonth <", value, "settlemonth");
            }
            return (Criteria) this;
        }

        public Criteria andSettlemonthLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settlemonth <=", value, "settlemonth");
            }
            return (Criteria) this;
        }

        public Criteria andSettlemonthIn(List<Integer> values) {
            addCriterion("settlemonth in", values, "settlemonth");
            return (Criteria) this;
        }

        public Criteria andSettlemonthNotIn(List<Integer> values) {
            addCriterion("settlemonth not in", values, "settlemonth");
            return (Criteria) this;
        }

        public Criteria andSettlemonthBetween(Integer value1, Integer value2) {
            addCriterion("settlemonth between", value1, value2, "settlemonth");
            return (Criteria) this;
        }

        public Criteria andSettlemonthNotBetween(Integer value1, Integer value2) {
            addCriterion("settlemonth not between", value1, value2, "settlemonth");
            return (Criteria) this;
        }

        public Criteria andSettledayIsNull() {
            addCriterion("settleday is null");
            return (Criteria) this;
        }

        public Criteria andSettledayIsNotNull() {
            addCriterion("settleday is not null");
            return (Criteria) this;
        }

        public Criteria andSettledayEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleday =", value, "settleday");
            }
            return (Criteria) this;
        }

        public Criteria andSettledayNotEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleday <>", value, "settleday");
            }
            return (Criteria) this;
        }

        public Criteria andSettledayGreaterThan(Integer value) {
            if (value != null) {
                addCriterion("settleday >", value, "settleday");
            }
            return (Criteria) this;
        }

        public Criteria andSettledayGreaterThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleday >=", value, "settleday");
            }
            return (Criteria) this;
        }

        public Criteria andSettledayLessThan(Integer value) {
            if (value != null) {
                addCriterion("settleday <", value, "settleday");
            }
            return (Criteria) this;
        }

        public Criteria andSettledayLessThanOrEqualTo(Integer value) {
            if (value != null) {
                addCriterion("settleday <=", value, "settleday");
            }
            return (Criteria) this;
        }

        public Criteria andSettledayIn(List<Integer> values) {
            addCriterion("settleday in", values, "settleday");
            return (Criteria) this;
        }

        public Criteria andSettledayNotIn(List<Integer> values) {
            addCriterion("settleday not in", values, "settleday");
            return (Criteria) this;
        }

        public Criteria andSettledayBetween(Integer value1, Integer value2) {
            addCriterion("settleday between", value1, value2, "settleday");
            return (Criteria) this;
        }

        public Criteria andSettledayNotBetween(Integer value1, Integer value2) {
            addCriterion("settleday not between", value1, value2, "settleday");
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeIsNull() {
            addCriterion("minconsumtype is null");
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeIsNotNull() {
            addCriterion("minconsumtype is not null");
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeEqualTo(Byte value) {
            if (value != null) {
                addCriterion("minconsumtype =", value, "minconsumtype");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("minconsumtype <>", value, "minconsumtype");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("minconsumtype >", value, "minconsumtype");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("minconsumtype >=", value, "minconsumtype");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeLessThan(Byte value) {
            if (value != null) {
                addCriterion("minconsumtype <", value, "minconsumtype");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("minconsumtype <=", value, "minconsumtype");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeIn(List<Byte> values) {
            addCriterion("minconsumtype in", values, "minconsumtype");
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeNotIn(List<Byte> values) {
            addCriterion("minconsumtype not in", values, "minconsumtype");
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeBetween(Byte value1, Byte value2) {
            addCriterion("minconsumtype between", value1, value2, "minconsumtype");
            return (Criteria) this;
        }

        public Criteria andMinconsumtypeNotBetween(Byte value1, Byte value2) {
            addCriterion("minconsumtype not between", value1, value2, "minconsumtype");
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountIsNull() {
            addCriterion("minconsumeamount is null");
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountIsNotNull() {
            addCriterion("minconsumeamount is not null");
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumeamount =", value, "minconsumeamount");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountNotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumeamount <>", value, "minconsumeamount");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountGreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumeamount >", value, "minconsumeamount");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountGreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumeamount >=", value, "minconsumeamount");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountLessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumeamount <", value, "minconsumeamount");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountLessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumeamount <=", value, "minconsumeamount");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountIn(List<BigDecimal> values) {
            addCriterion("minconsumeamount in", values, "minconsumeamount");
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountNotIn(List<BigDecimal> values) {
            addCriterion("minconsumeamount not in", values, "minconsumeamount");
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("minconsumeamount between", value1, value2, "minconsumeamount");
            return (Criteria) this;
        }

        public Criteria andMinconsumeamountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("minconsumeamount not between", value1, value2, "minconsumeamount");
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityIsNull() {
            addCriterion("minconsumequantity is null");
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityIsNotNull() {
            addCriterion("minconsumequantity is not null");
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumequantity =", value, "minconsumequantity");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityNotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumequantity <>", value, "minconsumequantity");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityGreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumequantity >", value, "minconsumequantity");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityGreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumequantity >=", value, "minconsumequantity");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityLessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumequantity <", value, "minconsumequantity");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityLessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("minconsumequantity <=", value, "minconsumequantity");
            }
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityIn(List<BigDecimal> values) {
            addCriterion("minconsumequantity in", values, "minconsumequantity");
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityNotIn(List<BigDecimal> values) {
            addCriterion("minconsumequantity not in", values, "minconsumequantity");
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("minconsumequantity between", value1, value2, "minconsumequantity");
            return (Criteria) this;
        }

        public Criteria andMinconsumequantityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("minconsumequantity not between", value1, value2, "minconsumequantity");
            return (Criteria) this;
        }

        public Criteria andPapertextIsNull() {
            addCriterion("papertext is null");
            return (Criteria) this;
        }

        public Criteria andPapertextIsNotNull() {
            addCriterion("papertext is not null");
            return (Criteria) this;
        }

        public Criteria andPapertextEqualTo(String value) {
            if (value != null) {
                addCriterion("papertext =", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextNotEqualTo(String value) {
            if (value != null) {
                addCriterion("papertext <>", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextGreaterThan(String value) {
            if (value != null) {
                addCriterion("papertext >", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextGreaterThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("papertext >=", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextLessThan(String value) {
            if (value != null) {
                addCriterion("papertext <", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextLessThanOrEqualTo(String value) {
            if (value != null) {
                addCriterion("papertext <=", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextLike(String value) {
            if (value != null) {
                addCriterion("papertext like", "%"+value+"%", "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextNotLike(String value) {
            if (value != null) {
                addCriterion("papertext not like", value, "papertext");
            }
            return (Criteria) this;
        }

        public Criteria andPapertextIn(List<String> values) {
            addCriterion("papertext in", values, "papertext");
            return (Criteria) this;
        }

        public Criteria andPapertextNotIn(List<String> values) {
            addCriterion("papertext not in", values, "papertext");
            return (Criteria) this;
        }

        public Criteria andPapertextBetween(String value1, String value2) {
            addCriterion("papertext between", value1, value2, "papertext");
            return (Criteria) this;
        }

        public Criteria andPapertextNotBetween(String value1, String value2) {
            addCriterion("papertext not between", value1, value2, "papertext");
            return (Criteria) this;
        }

        public Criteria andContaintypeIsNull() {
            addCriterion("containtype is null");
            return (Criteria) this;
        }

        public Criteria andContaintypeIsNotNull() {
            addCriterion("containtype is not null");
            return (Criteria) this;
        }

        public Criteria andContaintypeEqualTo(Byte value) {
            if (value != null) {
                addCriterion("containtype =", value, "containtype");
            }
            return (Criteria) this;
        }

        public Criteria andContaintypeNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("containtype <>", value, "containtype");
            }
            return (Criteria) this;
        }

        public Criteria andContaintypeGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("containtype >", value, "containtype");
            }
            return (Criteria) this;
        }

        public Criteria andContaintypeGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("containtype >=", value, "containtype");
            }
            return (Criteria) this;
        }

        public Criteria andContaintypeLessThan(Byte value) {
            if (value != null) {
                addCriterion("containtype <", value, "containtype");
            }
            return (Criteria) this;
        }

        public Criteria andContaintypeLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("containtype <=", value, "containtype");
            }
            return (Criteria) this;
        }

        public Criteria andContaintypeIn(List<Byte> values) {
            addCriterion("containtype in", values, "containtype");
            return (Criteria) this;
        }

        public Criteria andContaintypeNotIn(List<Byte> values) {
            addCriterion("containtype not in", values, "containtype");
            return (Criteria) this;
        }

        public Criteria andContaintypeBetween(Byte value1, Byte value2) {
            addCriterion("containtype between", value1, value2, "containtype");
            return (Criteria) this;
        }

        public Criteria andContaintypeNotBetween(Byte value1, Byte value2) {
            addCriterion("containtype not between", value1, value2, "containtype");
            return (Criteria) this;
        }

        public Criteria andAdditionalIsNull() {
            addCriterion("additional is null");
            return (Criteria) this;
        }

        public Criteria andAdditionalIsNotNull() {
            addCriterion("additional is not null");
            return (Criteria) this;
        }

        public Criteria andAdditionalEqualTo(Byte value) {
            if (value != null) {
                addCriterion("additional =", value, "additional");
            }
            return (Criteria) this;
        }

        public Criteria andAdditionalNotEqualTo(Byte value) {
            if (value != null) {
                addCriterion("additional <>", value, "additional");
            }
            return (Criteria) this;
        }

        public Criteria andAdditionalGreaterThan(Byte value) {
            if (value != null) {
                addCriterion("additional >", value, "additional");
            }
            return (Criteria) this;
        }

        public Criteria andAdditionalGreaterThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("additional >=", value, "additional");
            }
            return (Criteria) this;
        }

        public Criteria andAdditionalLessThan(Byte value) {
            if (value != null) {
                addCriterion("additional <", value, "additional");
            }
            return (Criteria) this;
        }

        public Criteria andAdditionalLessThanOrEqualTo(Byte value) {
            if (value != null) {
                addCriterion("additional <=", value, "additional");
            }
            return (Criteria) this;
        }

        public Criteria andAdditionalIn(List<Byte> values) {
            addCriterion("additional in", values, "additional");
            return (Criteria) this;
        }

        public Criteria andAdditionalNotIn(List<Byte> values) {
            addCriterion("additional not in", values, "additional");
            return (Criteria) this;
        }

        public Criteria andAdditionalBetween(Byte value1, Byte value2) {
            addCriterion("additional between", value1, value2, "additional");
            return (Criteria) this;
        }

        public Criteria andAdditionalNotBetween(Byte value1, Byte value2) {
            addCriterion("additional not between", value1, value2, "additional");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime =", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime <>", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            if (value != null) {
                addCriterion("createtime >", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime >=", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            if (value != null) {
                addCriterion("createtime <", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            if (value != null) {
                addCriterion("createtime <=", value, "createtime");
            }
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andServicechargeIsNull() {
            addCriterion("servicecharge is null");
            return (Criteria) this;
        }

        public Criteria andServicechargeIsNotNull() {
            addCriterion("servicecharge is not null");
            return (Criteria) this;
        }

        public Criteria andServicechargeEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("servicecharge =", value, "servicecharge");
            }
            return (Criteria) this;
        }

        public Criteria andServicechargeNotEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("servicecharge <>", value, "servicecharge");
            }
            return (Criteria) this;
        }

        public Criteria andServicechargeGreaterThan(BigDecimal value) {
            if (value != null) {
                addCriterion("servicecharge >", value, "servicecharge");
            }
            return (Criteria) this;
        }

        public Criteria andServicechargeGreaterThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("servicecharge >=", value, "servicecharge");
            }
            return (Criteria) this;
        }

        public Criteria andServicechargeLessThan(BigDecimal value) {
            if (value != null) {
                addCriterion("servicecharge <", value, "servicecharge");
            }
            return (Criteria) this;
        }

        public Criteria andServicechargeLessThanOrEqualTo(BigDecimal value) {
            if (value != null) {
                addCriterion("servicecharge <=", value, "servicecharge");
            }
            return (Criteria) this;
        }

        public Criteria andServicechargeIn(List<BigDecimal> values) {
            addCriterion("servicecharge in", values, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotIn(List<BigDecimal> values) {
            addCriterion("servicecharge not in", values, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("servicecharge between", value1, value2, "servicecharge");
            return (Criteria) this;
        }

        public Criteria andServicechargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("servicecharge not between", value1, value2, "servicecharge");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_price
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lm_price
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}